janis-commerce/view-schema-validator

- lib/schemas/common/mapper.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-611
Se debe poder indicar un mapper con el nombre `date`
El mapper debe poder aceptar las siguientes propiedades:
- format: String (opcional)
Se agrego a los mappers uno nuevo, validando su propiedades internas de format.
> JMV-611 mapper date

- lib/schemas/edit-new/modules/componentNames.js
- lib/schemas/edit-new/modules/components/others.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-654
Se debe poder indicar un nuevo componente en formularios con el nombre de ColorPicker
Se agrego al schema de edit new un nuevo componente de colorPicker cambiando el viejo que tenia que no se usaba.
> JMV-654-component-color-picker

- lib/schemas/edit-new/modules/componentNames.js
- lib/schemas/edit-new/modules/components/dateTimePicker.js
- lib/schemas/edit-new/modules/components/index.js
- lib/schemas/edit-new/modules/components/others.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-653
Se debe poder indicar un nuevo componente en formularios con el nombre de DateTimePicker
Se agrego al un nuevo componentes al edit-new DateTimePicker con las siguientes propiedades
- selectRange: Indicando si se debe mostrar un selector de rango (true) o un solo valor (false)
- selectDate: Indicando si se debe mostrar la selección de fecha (true) o no (false)
- selectTime: Indicando si se debe mostrar la selección de horario (true) o no (false)
> Jmv 653 component datetime picker

- lib/schemas/browse/modules/componentNames.js
- lib/schemas/browse/modules/components/index.js
- lib/schemas/browse/modules/components/sacClaimChange.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-699
Se debe poder definir un nuevo componente para los fields de un listado: SacClaimChange
Se agrego al componente de SacClaimChange en listados en general.
> JMV-699 add sacClaimChange component

- lib/schemas/edit-new/modules/components/checkList.js
- lib/schemas/edit-new/modules/components/index.js
- lib/schemas/edit-new/modules/components/others.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-719
Se debe soportar un nuevo component para los campos de un Form: Checklist
Debe aceptar los siguientes componentAttributes:
- optionsSource: Requerido. Tipo endpoint.
- sectionField: Requerido. String.
- groupField: Requerido. String.
- labelField: Requerido. String.
- valueField: Requerido. String.
- translateSectionLabel: Opcional. Booleano.
- translateGroupLabel: Opcional. Booleano.
- translateCheckboxLabel: Opcional. Booleano.
Se agrego al componente de Checklist las properties descriptas arriba.
> JMV-719 add checklist new properties validation

- lib/schemas/edit-new/modules/sections/formSection.js
- lib/schemas/edit-new/modules/sections/index.js
- lib/schemas/edit-new/modules/sectionsNames.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-742
Se debe poder declarar una sección FormSection que reciba los mismos parámetros del MainForm.
Se agrego a las secciones de edit una nueva sección con las properties del MainForm ademas se le agregaron a esta nuevas props de target y source.
> JMV-742 add formSection

- lib/schemas/browse/modules/componentNames.js
- lib/schemas/browse/modules/components/index.js
- lib/schemas/browse/modules/components/link.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-811
Se debe poder declarar un nuevo componente al schema de browse. El componte debe llamarse Link y debe tener las mismas propiedades que Link del schemas de edit-create.
Se agrego a los componentes del browse el componente Link.
> add link in browse

- lib/schemas/browse/modules/filters/componentNames.js
- lib/schemas/browse/modules/filters/components/dateTimePicker.js
- lib/schemas/browse/modules/filters/components/index.js
- lib/schemas/browse/modules/filters/components/input.js
- lib/schemas/browse/modules/filters/components/select-options/index.js
- lib/schemas/browse/modules/filters/components/select-options/localOptions.js
- lib/schemas/browse/modules/filters/components/select-options/remoteOptions.js
- lib/schemas/browse/modules/filters/components/select.js
- lib/schemas/browse/modules/filters/filters.js
- lib/schemas/browse/modules/filters/index.js
- lib/schemas/common/browseBase.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-836
https://fizzmod.atlassian.net/browse/JMV-840
El validador debe validar esta nueva propiedad de filters, manteniendo la propiedad vieja.
Tambien se agrego un nuevo componente para los filtros.
Se agregaron al browse base la propertie filters , con nuevos componentes como el dateTimePicker y el select como el de EditCreate, el input sigue igual.
> JMV-836 JMV-840 add new filters in browses

- lib/schemas/browse/modules/componentNames.js
- lib/schemas/browse/modules/components/index.js
- lib/schemas/browse/modules/components/multiValueWrapper.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-874
Se debe validar un nuevo componente MultiValueWrapper para los campos de listados, que tenga los siguientes component attributes:
field: Requerido. Un field de browse normal.
direction: Opcional. Enum de [horizontal, vertical]. Default vertical.
Se agrego un nuevo componente a los componentes de browse, con las properties definidas en el requerimiento.
> Jmv 874 multi value wrapper

- lib/schemas/edit-new/modules/componentNames.js
- lib/schemas/edit-new/modules/components/asyncWrapper.js
- lib/schemas/edit-new/modules/components/index.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-933
Se agregar un el componente AsyncWrapper en el new-edit  agregando una propiedad para poder pasar parámetros en el path o en query string (igual que los staticFilters del browse)
Se agregó componente AsyncWrapper a los componentes de edit/new agregandole una nueva prop con de staticFilters igual a los del browse.
> Jmv 933 edit create asyncwrapper

- lib/schemas/browse/modules/conditions/conditions.js
- lib/schemas/browse/modules/conditions/index.js
- lib/schemas/browse/modules/conditions/names.js
- lib/schemas/browse/modules/field.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-964
Se debe agregar una nueva propiedad conditions en los fields de listados, con la misma estructura de los Create/Edit.
Solo se debe aceptar la condición showWhen, no enableWhen
En filtros solo aplican los estáticos
Se agregó una nueva propertie al schema de fields de browse, agregando conditions y su schema igual al de edit/create, excepto por el enableWhen.
> add conditions in browse fields

- lib/schemas/browse/modules/filters/components/select-options/remoteOptions.js
- lib/schemas/common/staticFilters.js
- lib/schemas/edit-new/modules/options/remoteOptions.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-965
Se debe aceptar una nueva prop opcional endpointParameters en los componentAttributes de los selects y multiselects con la estructura de los StaticFilters
En filtros solo aplican los estáticos
Se agregó una nueva propertie al componente de Selects de filtros y edit/create para que tengan staticFilters
> Jmv 965 select endpoint parameters

- lib/schemas/edit-new/modules/components/fieldsArray.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-966
Se debe agregar un nuevo componentAttribute al FieldsArray de tipo número y opcional
Ver si se puede validar que maxElements sea mayor que minElements si ambos están setteados
Se agregó una nueva propertie al componente FieldsArray de maxElements como de describe en el requerimiento
> add maxelements in fieldsArray

- lib/schemas/edit-new/modules/componentNames.js
- lib/schemas/edit-new/modules/components/index.js
- lib/schemas/edit-new/modules/components/map.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-969
Se debe validar un nuevo componente de formularios:
component: Map
componentAttributes:
**showSearchBar**: boolean
**canAddMarkers**: boolean
**maxMarkersQuantity**: number
**fieldsMapping**: object <string:string>*
En filtros solo aplican los estáticos
Se agregó un nuevo componente a los componentes de edit/create con los requerido en la descripcion.
> add map component

- lib/schemas/edit-new/modules/componentNames.js
- lib/schemas/edit-new/modules/components/html.js
- lib/schemas/edit-new/modules/components/index.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1010
Se debe validar un nuevo componente HTML, con los siguientes componentAttributes:
**sourceField**: String (opcional). Define el campo que contiene una URL de donde obtener el HTML
Se agregó un nuevo componente a los componentes de edit/create.
> add html component shema y edit/create

- lib/schemas/edit-new/modules/sections/apiKeysSection.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1061
Se debe validar una nueva propiedad requerida como un string: idField en la sección de apiKeysSection.
Se agrego una la prop idField, requerida, a la seccion apiKeySection
> add new prop for apiKeySection

- lib/schemas/edit-new/schema.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
- tests/mocks/schemas/new.yml
https://fizzmod.atlassian.net/browse/JMV-1124
Se debe agregar dos nuevas propiedades al schemas de edit/create. Deben ser string opcionales
- saveRedirectUrl
- cancelRedirectUrl
Se agregaron al schema de edit/create dos nuevas properties tipo string opcionales.
> addnw props in edit create schemas

- lib/schemas/edit-new/modules/sections/imageFilesSection.js
- lib/schemas/edit-new/modules/sections/index.js
- lib/schemas/edit-new/modules/sectionsNames.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1127
Se debe agregar una nueva propiedad canCreate al schema de edit/create, sea opcional boolean.
Se agrego una nueva prop boolean opcional al schema de edit/create
> add image files section

- lib/schemas/browse/modules/components/multiValueWrapper.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-1170
Agregar propiedad useDataField al schema de MultiValueWrapper (Boolean-opcional)
Se agrego una nueva prop de useDataField con las properties descriptas arriba en el schema del compoenente de MultiValueWrapper.
> add new prop in multivaluewrapper schema

- lib/schemas/common/mapper.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1167
Se debe un nuevo mapper de sufijo
Se agrego un nuevo mapper con el nombre de suffix que tenga props y estas tenga la property value string 
> add suffix mapper schema

- lib/schemas/browse/modules/components/badgeLetter.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1172
Agregar las siguientes propiedades al schema de BadgeLetter
- **backgroundColorTheme** string-opcional
- **backgroundColorSource** string-opcional
- **fontColorTheme** string-opcional
- **fontColorSource** string-opcional
Se agregaron nuevas properties descriptas arriba al schema del componente de BadgeLetter,
> add new props in badgeletter schema

- lib/schemas/common/browseBase.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1168
Definir en listados nueva prop con un objeto `appearance` con prop `desktop`,`mobile` y `default`, que sea otro objeto que tenga las props `rowMinHeight` (opcional-number) y `rowVerticalAlign` (string-opcional-enum(`top`,`middle`, `bottom`))
Ejemplo
```
appearance:
desktop:
rowMinHeight: 70
rowVerticalAlign: top
```
Se agrego una nueva prop de appearance con las properties descriptas arriba en todos los Browses.
> add new props in browses

- lib/schemas/browse/modules/componentNames.js
- lib/schemas/browse/modules/components/index.js
- lib/schemas/browse/modules/components/userAsyncWrapper.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-1202
Agregar nuevo componenente en componentes de Browse llamado UserAsyncWrapper
Se agregó un nuevo componente sin properties llamado UserAsyncWrapper
> user async wrapper browse component schema

- lib/schemas/browse/modules/components/multiValueWrapper.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-1213
Agregar los componentAttributes opcionales al componente de MultiValueWrapper:
- isCollapsable: true|false|onlyMobile|onlyDesktop
- defaultStatus: open|closed
- itemsToShowWhenClosed: number
Se agregaron nuevas props al schema de componente de MultiValueWrapper
> add new props in multi value wrapper component

- lib/schemas/edit-new/modules/componentNames.js
- lib/schemas/edit-new/modules/components/chips.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1206
Agregar nuevo componenente de statusChip para edit/create
Se agregó un nuevo componente StatusChip en edit/create
> add statuschip in edit/creates

- lib/schemas/edit-new/modules/sections/commonProperties.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1221
Agregar propiedad de conditions a las secciones de edit/create
Se agregó una nueva propiedad  de conditions en las secciones 
> add conditions in sections

- lib/schemas/edit-new/modules/sections/components/topComponents.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1211
Agregar propiedad de conditions a las actions de los topComponenents de edit/create
Se agregó una nueva propiedad de conditions en las actions de los topComponenents de edit/create
> add conditions in actions top components

- lib/schemas/browse/modules/componentNames.js
- lib/schemas/browse/modules/components/asyncUserChip.js
- lib/schemas/browse/modules/components/index.js
- lib/schemas/browse/modules/components/userAsyncWrapper.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-1231
Se debe cambiar los nombres de UserAsyncWrapper por AsyncUserChip
Se cambiarion los nombres de UserAsyncWrapper por AsyncUserChip
> change name for userAsyncWrapper

- lib/schemas/edit-new/modules/sections/index.js
- lib/schemas/edit-new/modules/sections/omsOrderInfo.js
- lib/schemas/edit-new/modules/sectionsNames.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1245
Se debe agregar una nueva seccion para edit con el nombre de `OmsOrderInfo`
Se agregó un nuevo schema para la nueva seccion de OmsOrderInfo
> add omsOrderInfo in edit section

- lib/schemas/browse/modules/filters/componentNames.js
- lib/schemas/browse/modules/filters/components/index.js
- lib/schemas/browse/modules/filters/components/userSelector.js
- lib/schemas/edit-new/modules/componentNames.js
- lib/schemas/edit-new/modules/components/index.js
- lib/schemas/edit-new/modules/components/userSelector.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1243
Crear un componente para filtros de browse y para Edit/Creates llamado UserSelector,
**componentAttributes:**
- isMulti: boolean (optional)
Se agregaron los componentes nuevos de UserSelector en filtros de browse y de edit/create.
con los componentAttributes definidos en la descripcion.
> add user selector component

- lib/schemas/edit-new/modules/sections/formSection.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1289
Agregar targetEndpointParameters y sourceEndpointParameters al la seccion de FormSection. (Opcionales)
- name: someForm
rootComponent: FormSection
targetEndpointParameters: endpointParameters
Se agregaron las props nuevas a los FormSections.
> add endpointparameters in FormSections

- lib/schemas/common/mapper.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1296
Agregar la prop `addWhitespace`(boolean|optional) en los mapper de suffix y prefix 
Se agrego la prop `addWhitespace` a los mappers de suffix y prefix
> add new prop in prefix suffix mapper

- lib/schemas/browse/modules/components/asyncWrapper.js
- lib/schemas/browse/modules/field-appearance.js
- lib/schemas/browse/modules/field.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1333
Se deberá agregar una nueva prop llamada width al objeto appearance, opcional
Se agrego la prop width al schema de appearance de fields, Tambien en asyncWrappers de browse se saco de requeridos el dataMapping
> add appearance new prop

- lib/schemas/browse/modules/filters/components/userSelector.js
- lib/schemas/edit-new/modules/components/userSelector.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1330
Agregar nueva prop llama onlyActiveUsers que debe ser opcional y boolean, a los schemas del componente UserSelector
Se agrego la prop en los schemas de UserSelecetor
> add new prop for userSelector

- lib/schemas/edit-new/modules/components/input.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1382
Se debe agregar al schema de Input de edit/create un nuevo type "hidden"
Se agregó al los types de input de edit/create el type "hidden"
> add type hidden in inputs edit/create

- lib/schemas/edit-new/modules/components/map.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1379
Se debe agregar al schema las posibles keys de fieldsMapping para componente Map:
- street
- number
- neighborhood
- city
- state
- postalCode
- country
- lat
- lng
Se las posibles prop para el fieldMapping del componente Map
> JMV-1379 add changes for map properties

- lib/schemas/edit-new/modules/sections/omsControls.js
- lib/schemas/edit-new/modules/sectionsNames.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1419
Se debe agregar una nueva seccion en edit para Controles de oms ("OmsControls")
Se agregó una nueva seccion con el name "OmsControls"
> add oms controls section schema

- lib/schemas/edit-new/modules/sections/index.js
- lib/schemas/edit-new/modules/sections/multiSection.js
- lib/schemas/edit-new/modules/sectionsNames.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1452
Se deberá generar un tipo de sección nueva
La sección se deberá llamar MultiSection
Deberá recibir un array de secciones, en principio solo BrowseSections
Se deberá poder declarar que sección es la que arranca como “activa”
Se agregó una nueva Seccion llamada MultiSection, a la que solo se pueden agregar subsecciones de Browse y se puede definir una defaultSection
> add multisection section

- lib/schemas/edit-new/modules/sections/components/topComponents.js
- package.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1519
Se deberán poder pasar esta propiedades de forma opcional
- icon
- iconColor
- color
- backgroundColor
Se agregaron nuevas properties para el Componente ActionForm de TopComponents 
> add new props for action form

- lib/schemas/edit-new/modules/sections/comments.js
- lib/schemas/edit-new/modules/sections/index.js
- lib/schemas/edit-new/modules/sectionsNames.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1542
Se deberá agregar una nueva seccion para comentarios en edit/create page
Se agregó una nueva sección en edit/create con el nombre de Comments
> add comments section

- lib/schemas/common/graphs.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-1559
Se debe agregar unas nuevas props al schema de graphs para poder poder mappear la data en otro desarrollo
Se agrego las nuevas props al schema de graphs para poder mappear la data.
> add graphs mapping schema

- lib/schemas/edit-new/modules/sections/index.js
- lib/schemas/edit-new/modules/sections/omsOrderHistory.js
- lib/schemas/edit-new/modules/sectionsNames.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1539
Se debe agregar una nueva seccion para el Historoal de una orden, se nos entrego un schema de ejemplo a seguir para crear la seccion descripta en la tarea.
Se agrego la nueva seccion con el nombre de OmsOrderHistory con las properties de schema descriptas en la tarea.
> Jmv 1539 oms order history section schema

- lib/schemas/edit-new/modules/headerProperties.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1577
Se debe agregar al al schema de header title, la properties de components.
Se agregó al schema de haeader title la properties de componentes con anteriores componentes y se agregaon nuevos.
> Jmv 1577 schema header title

- lib/schemas/edit-new/modules/componentNames.js
- lib/schemas/edit-new/modules/components/iconSelector.js
- lib/schemas/edit-new/modules/components/index.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1599
Se crear un nuevo componente para edi/create llamado IconSelector.
Se creó un nuevo componente IconSelector sin ninguna tipo de config adicional.
> JMV-1599 add schema for icon selector component

- lib/schemas/browse/modules/components/link.js
- lib/schemas/edit-new/modules/components/link.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1636
Se deberan agregar las siguientes properties al componente Link de los edit/Create y browses. 
- urlTarget: SOURCE_ENDPOINT
- endpointParameters: ENDPOINT_PARAMETERS
Se agrego al schema del componente Link de browse y forms nuevas props.
> add new prop for link components

- lib/schemas/common/actions/action.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1613
Se debe agregar una nueva property target a las action buttons
Se agrego al schema de action tipo link una prop "target" tipo sourceEndpoint
> add new prop for action link

- lib/schemas/browse/modules/components/icon.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-1632
Sacar de props requeridas la prop icon del componente Icon y se agrego una nueva props de useTheme
Se saco de props requerida icon y se agregó una nueva para useTheme
> Jmv 1632 change props icon component

- lib/schemas/browse/modules/components/chips.js
- lib/schemas/browse/modules/components/icon.js
- lib/schemas/common/conditions/conditions.js
- lib/schemas/common/conditions/index.js
- lib/schemas/common/conditions/names.js
- lib/schemas/edit-new/modules/components/chips.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1702
Se deberá agregar la property *themeConditionals*
Se deberá usar la misma idea de los condicionales para los fields
Se deberán agregar las siguientes nuevas condiciones:
- greaterThan => mayor que
- greaterOrEqual => mayor o igual que
- lowerThan => menor que
- lowerOrEqual => menos o igual que
La nueva property deberá incluirse en los siguientes componentes:
- Chip
- StatusChip
- Icon
Se agregaron nuevas props a los componentes y se agregaron nuevas props a los condicionales en general.
> add new props for conditionals

- lib/schemas/edit-new/modules/components/code.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1701
Se deberá poder agregarle al componente Code de forma opcional las siguientes properties:
**Width**
- number
**Height**
- number
- string(enum)
- - medium
- - large
- - full
Se agrego al schema del componente Code las prop descriptas en la descripcion
> Jmv 1701 code component new props

- lib/schemas/common/conditions/names.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1702
Se cambiaron los nombres de condiciones que estaban mal
> change conditions names

- lib/schemas/edit-new/modules/sections/components/fieldGroup.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1726
Se deberá agregar una nueva property el componente fieldsGroup
Se deberá poder determinar si por default se puede colapsar o no
La nueva property se deberá llamar defaultOpen: true/false
Se agrego al schema del componente fieldsGroup las prop descripta en la descripcion
> add defaultOpen prop

- lib/schemas/browse/modules/components/badgeLetter.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1728
Se deberá agregar la property useTheme al componente BadgeLetter
Se agrego al schema del componente BadgeLetter las prop descripta en la descripcion
> add badgeletter useTheme prop

- lib/schemas/edit-new/modules/components/code.js
- lib/schemas/edit-new/modules/components/html.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1701
Se deberá poder agregarle al componente HTML de forma opcional las siguientes properties:
Width:
- number
Height:
- number
- string(enum)
- medium
- large
- full
Se agrego al schema del componente HTML las prop descriptas en la descripcion y se las borro de Code
> move props code to html

- lib/schemas/edit-new/modules/componentNames.js
- lib/schemas/edit-new/modules/components/index.js
- lib/schemas/edit-new/modules/components/selectForm.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1787
Implementar el nuevo componente SelectForm en los formularios.
Similar a los select sin algunas props y con unas nuevas detalladas en la tarea.
Se agrego el nuevo componente SelectForm a los schemas components de los forms.
> Jmv 1787 select form schema

- lib/schemas/edit/schema.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1817
Se deberá agregar al schema del Edit la prop canPrint (boolean).
Se agrego al schema de edit la prop de canPrint de tipo boolean.
> add canPrint prop in edit

- lib/schemas/browse/modules/field.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-1796
Se deberá permitir la posibilidad de agregar a los Field de Browse la prop showOnPreview (boolean).
Se agrego al schema de los field de los browse la nueva prop "showOnPreview".
> add prop for browse field

- lib/schemas/common/browseBase.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-1882
Se deberá poder pasarle una prop al browseSection para determinar el path a donde deberá redireccionar
rowLinkPath: /route/{id}/edit
Se agrego una nueva prop para todos los browses (rowLinkPath- string)
> add new props for browses

- lib/schemas/common/browseBase.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1882
Se deberá poder pasarle una prop al browseSection para determinar el path a donde deberá redireccionar
Se agrego una nueva prop para todos los browses rowLink(_object_) con dos properties
- path(_string_-required)
- endpointParameters(_endpointParameters_ - optional)
> change row link prop

- lib/schemas/edit-new/modules/sections/index.js
- lib/schemas/edit-new/modules/sections/multiSection.js
- lib/schemas/edit-new/modules/sections/summary/cardNames.js
- lib/schemas/edit-new/modules/sections/summary/cards/baseCard/baseCard.js
- lib/schemas/edit-new/modules/sections/summary/cards/baseCard/fieldsGroup.js
- lib/schemas/edit-new/modules/sections/summary/cards/baseCard/index.js
- lib/schemas/edit-new/modules/sections/summary/cards/index.js
- lib/schemas/edit-new/modules/sections/summary/commonCardsProps.js
- lib/schemas/edit-new/modules/sections/summary/index.js
- lib/schemas/edit-new/modules/sections/summary/summary.js
- lib/schemas/edit-new/modules/sectionsNames.js
- lib/schemas/edit-new/schema.js
- lib/schemas/utils.js
- package-lock.json
- package.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
- tests/schema-utils-test.js
https://fizzmod.atlassian.net/browse/JMV-1875
Se deberá agregar una nueva sección de Summary con un schema similar al de los Dashboard
Se agrego una nueva seccion de summary en los edits
> add schema summary

- lib/schemas/browse/modules/components/actionButtons.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-1912
Agregar callback "reloadRow" para actionbuttons de browse
Se agrego un nuevo tipo de callback para las actionsButtons de browse.
> add reload row callback

- lib/schemas/browse/modules/filters/components/select-options/remoteOptions.js
- lib/schemas/edit-new/modules/options/remoteOptions.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit-with-sources.yml
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit-with-sources.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1903
Se deberá cambiar properties para los selects/multiselects remotos, para tener una mejor usabilidad en la implementacion.
Se cambiaron values y defaults para serachParam, valuesMapper y initialValuesEndpoint.
> changes in remote selects options

- lib/schemas/common/mapper.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-1921
Agregar nuevo mapper (arrayMap), que tome de un array de objetos y devuleva un array con una o un cojunto de properties de cada objeto de array.
Se agrego el nuevo mapper a los mappers y se agregaron las properties para poder definir si se toma una propertie de cada objeto o se usa un  template para tomar varias.
> add arrayMapp mapper

- lib/schemas/browse/modules/components/link.js
- lib/schemas/browse/modules/filters/components/select-options/remoteOptions.js
- lib/schemas/browse/modules/interactions.js
- lib/schemas/common/actions/action.js
- lib/schemas/common/browseBase.js
- lib/schemas/common/endpointParameters.js
- lib/schemas/common/graphs.js
- lib/schemas/definitions/index.js
- lib/schemas/edit-new/modules/components/asyncWrapper.js
- lib/schemas/edit-new/modules/components/link.js
- lib/schemas/edit-new/modules/options/remoteOptions.js
- lib/schemas/edit-new/modules/sections/components/topComponents.js
- lib/schemas/edit-new/modules/sections/formSection.js
- lib/schemas/edit-new/modules/sections/orderItemsSection.js
- lib/schemas/edit-new/modules/sections/section-files/imageFilesSection.js
- lib/schemas/edit-new/modules/triggers/triggers.js
- lib/schemas/edit/schema.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1900
Se deberá deprecar los staticFilters a un mes para adelante.
Se deberá brindar soporte en ese lapso con los endpointParameters
Se cambiaron nombres de metodos y variables para eliminar staticFilters, se dejaron las que se usan por ahora y se agregaron las nuevas props de endpointParameters para reemplazar estas.
Se paso a definitions los endpointParameters para su uso mas sencillo.
> Jmv 1900 compatibility staticfilter endpointparameters

- lib/schemas/common/browseBase.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-1942
Agregar nueva prop al schema de browses definida en la descripcion de la tarea.
Se agrego el la nueva props massiveActions en el schema de browses definida en la tarea.
> add masive actions schema

- lib/schemas/browse/modules/components/actionButtons.js
- lib/schemas/common/actionCallbacks.js
- lib/schemas/common/topComponents.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1986
Se deberá agregar un nuevo callback redirect para redireccionar a una url en los casos de existo.
Se deberá poder pasar un path, target y endpointParameters.
Se agrego un nuevo callback generico(redirect), con las props necesarias para su funcionamiento, tambien se hizo un refactor de los callbacks en general para su mejor funcionamiento.
> Jmv 1986 new callbacks top components

- lib/schemas/edit-new/modules/components/fieldsArray.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-1985
Agregar nuevos properties en componentAttributes de los FieldsArray
- addButtonText: string que se debe traducir
- addButtonTextColor: string color
- addButtonBackgoundColor: string color
- addButtonIcon: string  icon name
Se agrego al schema de FieldsArray las nuevas props descriptas arriba,
> add new props for FieldsArray

- lib/schemas/edit-new/modules/componentNames.js
- lib/schemas/edit-new/modules/components/index.js
- lib/schemas/edit-new/modules/components/objectCreator.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2053
Se deberá agregar un componente nuevo a los Forms, ObjectCreator sin ningun tipo de componentAttrbutes.
Se agrego el nuevo componente a los Forms
> add object creator component schema

- lib/schemas/edit-new/modules/field.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2054
Se deberá agregar un nuevo property (dependecy: string) a los Fields de los Forms.
Se agrego la prop dependency al schema de los Fields de Forms
> add dependency prop

- lib/schemas/edit-new/modules/components/input.js
- lib/schemas/edit-new/modules/components/others.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2048
Se deberá agregar los componentes Input, Textarea, Switch y Checkbox, una nueva prop en componentAttributes, autoComplete(boolean)
Se agrego la prop en componentAttrbutes en los componetes descriptos arriba
> add autocomplete prop

- lib/schemas/browse/modules/field.js
- lib/schemas/common/browseBase.js
- lib/schemas/common/dependencies.js
- lib/schemas/definitions/index.js
- lib/schemas/edit-new/modules/sections/formSection.js
- lib/schemas/edit-new/modules/sections/mainForm.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2063
Se deberá agregar el schema de dependencies descripto en en la historia padre, para los Forms en general y a los Browses.
Tambien se agrego la prop dependency al  Field de browse
Se agrego el schema dependecies generico, se lo agrego a los browses y form. Tambien se agregó la prop dependency al field de Browse
> add dependencies schemas

- lib/schemas/edit-new/modules/sections/summary/cardNames.js
- lib/schemas/edit-new/modules/sections/summary/cards/index.js
- lib/schemas/edit-new/modules/sections/summary/cards/omsCards.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2081
Se debe agregar componentes de oms a la seccion de Summary
- OMSOrderShippingCard
- OMSOrderPickingCard
- OMSOrderStepsCard
- OMSOrderTotalsCard
- OMSOrderCustomerCard
- OMSOrderPaymentsCard
Se agregaron los componentes para la seccion de summary descriptos arriba
> add summary oms components

- lib/schemas/edit-new/modules/field.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2122
Se debe agregar un nueva prop placeholder(string) a los fields de los Forms.
Se agregó la nueva prop placeholder al field de los forms
> add placeholder prop field form

- lib/schemas/edit-new/modules/field.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2117
Se debe agregar un nueva prop position(left || right) a los fields de los Forms.
Se agregó la nueva prop position(left || right) al field de los Forms.
> add form field position prop

- lib/schemas/common/mapper.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
Se debe agregar un nuevo mapper template con las propeties de template y fields
Se agregaron a los mappers un nuevo mapper template con las properties template(string) y fields(array of strings)
> add mapper template

- lib/schemas/common/dependencies.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2126
Se debe agregar un nueva prop(searchMethod) a las dependencies. Que puede ser igual a `find` o `filter`
Se agregó la nueva prop searchMethod a la dependency
> add searchMethod prop in dependencies

- lib/schemas/common/endpointParameters.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
Se debe agregar nuevas types en endpointParameters (filter, queryStirng, body)
Se agregaron las nuevas types en el schema de endpointParameters
> add new types for endpointParameters

- lib/schemas/edit-new/modules/components/selects.js
- lib/schemas/edit-new/modules/components/statusSelector.js
- lib/schemas/edit-new/modules/components/userSelector.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2129
Se debe agregar un nueva prop creatable(boolean) en Selects
- Selects/Multiselects
- UserSelector
- StatusSelector
Se agregó la nueva prop creatable(boolean) a los selects mencionados en la descripcion
> add creatable prop in select components

- lib/schemas/edit-new/modules/sections/index.js
- lib/schemas/edit-new/modules/sections/remoteSection.js
- lib/schemas/edit-new/modules/sectionsNames.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2128
Se debe agregar un nueva seccion para los edits, con el nombre RemoteSection
- source: sourceEndpoint
- target: sourceEndpoint
- overwriteName: string
- sourceField: string
- schemaSource: Object(
- - type: string('static'||'dynamic') 
- - endpoint: sourceEndpoint
- - endpointParameters: endpointParameters
Se agregó la nueva seccion de remoteSection con las properties descriptas.
> Jmv 2128 remote section schema

- lib/schemas/browse/modules/components/texts.js
- lib/schemas/edit-new/modules/components/index.js
- lib/schemas/edit-new/modules/components/others.js
- lib/schemas/edit-new/modules/components/text.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2153
Se debe agregar al componente text general de de todas las secciones unas nuevas props para que puedan tener icon y iconColor
Se agregaron las nuevas props de icon y iconColor a los componentes de text
> add text new props

- lib/schemas/edit-new/modules/sections/remoteSection.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
Se debe cambiar una prop que estaba mal el type
Se cambio la prop overwriteName de las secciones remotas de type stirng a boolean
> fix prop overwritename in remote section

- lib/builder.js
- lib/schemas/preview/actions/action.js
- lib/schemas/preview/actions/actions.js
- lib/schemas/preview/actions/index.js
- lib/schemas/preview/schema.js
- tests/builder-multiple-files-test.js
- tests/mocks/schemas/expected/preview.json
- tests/mocks/schemas/preview.yml
https://fizzmod.atlassian.net/browse/JMV-2159
Se debe agregar acciones nuevas para el header de Preview.
Se agregaron las nuevas acciones para el header del preview 
> Jmv 2159 actions preview

- lib/schemas/common/browseBase/browseBase.js
- lib/schemas/dashboard/schema.js
- lib/schemas/definitions/index.js
- lib/schemas/edit-new/modules/sections/summary/cardNames.js
- lib/schemas/edit-new/modules/sections/summary/cards/baseCard/baseCard.js
- lib/schemas/edit-new/modules/sections/summary/cards/graphCard.js
- lib/schemas/edit-new/modules/sections/summary/cards/index.js
- lib/schemas/edit-new/modules/sections/summary/cards/omsCards.js
- lib/schemas/edit-new/modules/sections/summary/commonCardsProps.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2174
Se debe agregar nuevo schema para la card de graficos en summary
Se agregó una nueva cards para los summary de graficos, y se hizo un pequeño refactor de las cards en gral
> add card graph schema

- lib/schemas/edit-new/modules/sections/components/fieldGroup.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
Se debe agregar conditions a los fieldsGroups
Se agrego la prop de conditions para los fieldsGroups
> add conditions for fieldGroups

- lib/schemas/edit-new/modules/field.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2190
- Los fields deberán poder recibir un ancho mediante la prop width(number) (se interpreta como porcentaje)
- La prop llegara en el root del componente.
Se agrego la nueva prop de width a los fields de forms
> add with prop to edit field

- lib/schemas/common/browseBase/browseBase.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse-not-actions.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2191
Se debe agregar una nueva prop statusBar para browses
statusBar:
field: fieldName // string-opcional
hide: boolean // boolean-opcional
useTheme: true || themeName // string || boolean - opcional
themeConditionals: [conditions_themes] // opcional
Se agregó la prop de statusBur con las propeties descriptas arriba, para todos los browseSections
> add status bar schema

- lib/schemas/common/endpointParameters.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
Se debe agregar a los endpointParameters staticos un nuevo valor posible(boolean)
Se agregó el type boolean a los valores posibles del endpointParameter static
> add static boolean value for endpointParameters

- lib/schemas/edit-new/modules/sections/remoteSection.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2225
Se debe agregar una nueva prop para seccion RemoteSection.
Se agregó la prop targetEndpointParameters a la seccion RemoteSection.
> add new prop for remoteSection

- lib/deprecation-validators/index.js
- lib/deprecation-validators/title-components-deprecation.js
- lib/deprecation-validators/title-deprecation.js
- lib/helpers/index.js
- lib/schemas/edit-new/modules/headerProperties.js
- tests/mocks/schemas/expected/edit.json
- tests/mocks/schemas/expected/preview.json
- tests/mocks/schemas/preview.yml
https://fizzmod.atlassian.net/browse/JMV-2256
- Se deberá eliminar el nivel de components dentro del title header.title
- Agregar los casos de los casos deprecados en el validador
- Se deberá tener en cuenta los componentes IdText, DefaultTitle y CustomTitle
- Se deberá tener en cuenta la key components
Se agregó el nuevo componente MainTitle y se cambio header.title para que pueda ser un array de componentes.
Tambien de agregaron las deprecations warnings.
> Jmv 2256 header title schema

- lib/schemas/edit-new/modules/sections/browseSection.js
- lib/schemas/edit-new/modules/sections/formSection.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
Agregar property sourceField en browse y Form sections
Se agregó a las secciones de Browse y Form la property sourceField(string) y en browseSection, se valida que tenga alguna al menos.
> Browse form section sourcefield

- lib/schemas/common/endpointParameters.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2266
Dentro de endpointParameters va a haber una nueva prop mapper para definir el formato con el que saldrá la data.
Ejemplo de los endpointParameters
endpointParameters:
- name: id
target: filter
value:
dynamic: locations
mapper: date
- name: id
target: body
value:
dynamic: locations
mapper: camelCase
Se agregó una property en el schema de los endpointParameters.
> add new prop for endpointParameters

- lib/schemas/edit-new/modules/headerProperties.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2269
Se deberá poder agregar todos los componentes existentes a la property title
Chips
Icon
Image
UserImage
Color
Se agregaron nuevos componentes al header de edit preview, descriptos mas arriba.
> add new components for header edit preview

- lib/schemas/common/browseBase/rowCollapse.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-2276
Se deberá agregar  la property previewSource en rowCollapse:
```
rowCollapse:
previewSource:
service: delivery
namespace: shipping
method: preview
```
Se agregó la prop previewSource en rowCollapse de los browses.
> add previewSource prop in rowCollapse

- lib/schemas/edit-new/modules/componentNames.js
- lib/schemas/edit-new/modules/components/index.js
- lib/schemas/edit-new/modules/components/newDatePicker.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2296
Se deberá agregar un nuevo componente NewDatePicker para los Forms, con las properties del antiguo DateTimePicker
Se agregó el componente NewDatePicker para forms
> add schema for new date picker

- lib/schemas/common-sections/sections/summary/commonCardsProps.js
- lib/schemas/common/graphs.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/preview.json
- tests/mocks/schemas/preview.yml
Se deberá agregar la opcion de de auto en la prop de height en los summary cards y graficos
Se agregó el componente NewDatePicker para forms
> add height prop

- lib/schemas/browse/modules/filters/components/userSelector.js
- lib/schemas/edit-new/modules/components/userSelector.js
- lib/schemas/monitor/cards/BaseCard.js
- lib/schemas/monitor/cards/cardNames.js
- lib/schemas/monitor/cards/index.js
- lib/schemas/monitor/schema.js
- tests/mocks/schemas/expected/monitor.json
- tests/mocks/schemas/monitor.yml
https://fizzmod.atlassian.net/browse/JMV-2407
Se debe agregar el schema a los fields de monitor.
Se agregó el schema de BaseCard para los fields de monitor.
Tambien se agregaron endpointParameters en el monitor.
> Jmv 2407 monitor schema changes

- lib/schemas/common/browseBase/browseBase.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
**https://fizzmod.atlassian.net/browse/JMV-2485**
Se debe agregar una nueva opcion(none) a las que existen en la property de pageSize de los browse.
Se cambió agregó la opcion "none" a los que ya existian en la property pageSize de browses.
> add pageSize browse new option

- lib/schemas/common/autoRefresh.js
- lib/schemas/common/browseBase/browseBase.js
- lib/schemas/definitions/index.js
- lib/schemas/monitor/schema.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse.json
**https://fizzmod.atlassian.net/browse/JMV-2495**
Se debe agregar la property de autoRefresh a los browses. Se cambió la property de autoRefresh para que pueda ser boolean ademas de numeros.
Se agregó la property de autoRefresh a los browses. Se cambio el schema de autoRefresh para que pueda ser boolean tambien.
> add autoRefresh changes and add prop in browse base schema

- lib/schemas/common/mapper.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse.json
**https://fizzmod.atlassian.net/browse/JMV-2523**
Se deberá agregar una nueva prop incomingFormat al usar el mapper date
La misma deberá ser opcional
Se agregó una nueva property para las props del mapper date.
> add new prop for mapper date

- lib/schemas/common/browseBase/massiveActions.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse.json
**https://fizzmod.atlassian.net/browse/JMV-2553**
Se deberá poder definir acciones masivas desde el schema
Se deberá poder pasar un array de acciones
Se agregó una nueva property actions para las massiveActions de los browses
> add generic actions into massive actions

- lib/schemas/common-sections/sections/summary/summary.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
**https://fizzmod.atlassian.net/browse/JMV-2555**
Se deberá poder agregar dependencies para dicha sección
Se agregó una nueva property dependencies para las secciones de summary 
> add dependencies in summary section

- lib/schemas/edit-new/modules/components/selects.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2569
Se deberá settear en una property targetField del select en donde: 
En caso de ser un string se debera guardar en esa variable todo el objecto
En caso de ser un objecto, se generara un field por cada key
Se agregó una nueva property targetField en componentAttributes en los Selects
> add new prop for select in form

- lib/schemas/browse/modules/interactions.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-2595
Agregar prop `sourceField` para las interacciones, de ListTooltip y Modal. 
Implementar condicionales para mostrar o no dicha interacción. 
Tanto los condicionales como el valor de field se deben tomar de la rowDara actual
Se agregaron nuevas properties a las interacciones dinamicas. Se agregaron las props de conditionals(conditionals) y sourceField(string)
> add new props for browse interactions

- lib/schemas/edit-new/modules/components/map.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2601
Se deberá poder pasar una prop drawRoute (true/false) al componente de Map.
Se agregó la nueva property al componente Map.
> add prop drawRoute in map component

- lib/schemas/browse/modules/interactions.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-2595
Agregar prop `sourceField` para las interacciones, de ListTooltip, Modal y Tooltip. 
Implementar condicionales para mostrar o no dicha interacción. 
Tanto los condicionales como el valor de field se deben tomar de la rowDara actual
Se agregaron nuevas properties a las interacciones dinamicas. Se agregaron las props de conditionals(conditionals) y sourceField(string)
> add sourceField prop in tooltip

- lib/schemas/browse/modules/filters/components/select-options/remoteOptions.js
- lib/schemas/common/mapper.js
- lib/schemas/common/template.js
- lib/schemas/definitions/index.js
- lib/schemas/edit-new/modules/components/location.js
- lib/schemas/edit-new/modules/headerProperties.js
- lib/schemas/edit-new/modules/options/remoteOptions.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
Se deberá modificar los fields de los mapper de template, para que puedan ser objetos que reciban:
name, conditions y mappers.
Se modificaron los lugares donde se usan el mapper de template para que use uno generico y se le agrego la modificacion a los fields.
> add modification for template mapper

- lib/schemas/common-sections/sections/summary/cardNames.js
- lib/schemas/common-sections/sections/summary/cards/index.js
- lib/schemas/common-sections/sections/summary/cards/stepsCard.js
- lib/schemas/edit-new/modules/componentNames.js
- lib/schemas/edit-new/modules/components/index.js
- lib/schemas/edit-new/modules/components/steps.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2657
Se deberá generar una componente copiando el diseño y funcionalidad de la card de steps de OMS
Se deberá poder implementar en un Edit
Se deberá poder implementar en un summary (agregar nueva card con la misma funcionalidad)
Se deberá poder definir un array steps posibles en los que se deberá mostrar en la card
Se deberán mostrar solo los steps que se puedan obtener de la data
En caso de ser un array, se deberá poder definir un campo del que deberá ir a buscar de cada objeto para ver si existe o no el step
En caso de ser un objeto, se deberá usar la key como fiel para validar si existe el step o no
Se deberá poder definir las siguientes propiedades:
icon => icono a mostrar en cada step
label …
> add schema steps card and component

- lib/schemas/edit-new/modules/field.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2689
Se debe agregar una nueva property para los Fields de Forms. La nueva property se deberá llamar defaultValueField
Se agregó la property defaultValueField en el schema de los FormFields
> add new prop defaultValueField

- lib/schemas/common-sections/sections/multiSection.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
https://fizzmod.atlassian.net/browse/JMV-2693
Se deberá poder incluir secciones remotas dentro del componente MultiSection
Se modificó el schema de la seccion de MultiSection para que puedan agregar RemoteSection en las subsections.
> add multiSection subsection remoteSection

- lib/schemas/browse/schema.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/expected/browse.json
https://fizzmod.atlassian.net/browse/JMV-2735
https://fizzmod.atlassian.net/browse/JMV-2734 (Historia)
Agregar conditions a las actions de la pagina de browse.
Se modificó el schema de actions del schema de browse para agregarlos conditions.
- Add conditions in browse page actions
> add conditions in actions page browse

- lib/schemas/browse/modules/components/chips.js
- lib/schemas/edit-new/modules/components/chips.js
- tests/mocks/schemas/browse.json
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/browse.json
- tests/mocks/schemas/expected/edit.json
- tests/mocks/schemas/expected/monitor.json
- tests/mocks/schemas/monitor.yml
https://fizzmod.atlassian.net/browse/JMV-2746
Agregar las nuevas props en el chip para que acepte un link
Se agregaron las nuevas props en los chips
-
-
> validator link in chip

- lib/schemas/common/graphs.js
- tests/mocks/schemas/dashboard.yml
- tests/mocks/schemas/expected/dashboard.json
Link al ticket
https://fizzmod.atlassian.net/browse/JMV-2840
Descripción del requerimiento
Se debe agregar nuevas properties para agregar el valor percent y value para las Card custom de Kpi
Descripción de la solución
Se agregaron las props value y percent con sus mappers correspondiente.
Changelog
-  Add new properties for graphs schema
```
> New keys custom card kpi

- lib/schemas/edit-new/modules/components/code.js
- tests/mocks/schemas/edit.yml
- tests/mocks/schemas/expected/edit.json
Agregar un par de nuevas props para el componente Code.
Para poder setearle las un minimo y maximo de lineas visibles.
Se agregaron las properties minLines y maxLines como tipo number al componente de Code.
```
- Add  minLines and maxLines property in Code component
```
> add new props for Code component

- lib/schemas/common/conditions/conditions.js
Esta rompiendo el validador
Me estaba pisando las properties en los if, dejando sin las demas props que necesitan los condicionales.
- Separe las props base en una constante y le paso el spread a properties
- npm t
- node index.js validate -i tests/mocks/schemas/schema-name.yml (reemplazar nombre del schema y extension)
> fix conditions
