lib/schemas/edit-new/modules/sections/commonProperties.js
lib/schemas/edit-new/modules/sections/topComponents.js
lib/schemas/edit-new/schema.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-569
Escenario #1: Validación de back
Se debe validar un nuevo campo **topComponents** dentro de todos los EditSections, el cual reciba las siguientes props:
**components**: Array de objetos con las siguientes props:
**component**: nombres del componente.
**attributes**: objeto opcional libre de atributos
Se agrego la el schema pra topComponents con sus respectivas properties y se lo agrego a las properties custom de las sections de edit y new

add top component validation in sections

---

lib/schemas/edit-new/modules/sections/topComponents.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-583
Se debe validar un nuevo campo topComponents dentro de todos los EditSections, el cual es un Array con Objetos que reciban las siguientes props:
- 
- component: nombres del componente.
- 
- attributes: objeto opcional libre de atributos
Se agrego la el schema pra topComponents con sus respectivas properties y se lo agrego a las properties custom de las sections de edit y new

fix topComponent validation

---

lib/schemas/browse/schema.js
lib/schemas/common/browseBase.js
lib/schemas/edit-new/modules/sections/browseSection.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-625
Se debe poder indicar en el schema de browse (ya sea la página o una BrowseSection), una propiedad staticFilters con la definición de filtros que se agregarán en todas las peticiones de data.
Se agregaron las validaciones de staicFilters en los browse de Section y en la page diferenciando sus staticFilter values

JMV-625 add static filters

---

lib/schemas/edit-new/schema.js
tests/endpoint-resolver-test.js
tests/mocks/schemas/edit-with-sources.yml
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit-with-sources.json
tests/mocks/schemas/expected/edit.json
tests/mocks/schemas/new.yml

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-625
Se debe poder indicar la propiedad target en los schemas, y debe ser un endpoint válido (service, namespace y method)
Se agrego al schema de edit new una nueva propiedad "target" tipo endpoint requerido

add target in shema new edit

---

lib/schemas/common/browseBase.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-625
Se debe poder indicar en el schema de browse (ya sea la página o una BrowseSection), una propiedad staticFilters con la definición de filtros que se agregarán en todas las peticiones de data.
Se agregaron las validaciones de staicFilters en los browse de Section y en la page diferenciando sus staticFilter values. Se agregaron mas tipos para el filtro con value static

add types in static filters

---

README.md
index.js
lib/builder.js
lib/endpoint-resolver.js
lib/schemas/common/browseBase.js
lib/view-schema-validator.js
tests/builder-multiple-files-test.js
tests/builder-single-files-test.js
tests/endpoint-resolver-test.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json
tests/view-schema-validator-test.js

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-629
Se debe agregar opcion al yargs y pasarle al EndpointResolver el environment correspondiente para que pueda resolver bien los endpoints.
Se agregó la opcion `env` en yargs y se fue pasando el valor de la opcion hacia  la instancia de EndpointResolveLocal.

JMV-629 add env option

---

lib/schemas/edit-new/modules/components/index.js
lib/schemas/edit-new/modules/components/link.js
lib/schemas/edit-new/modules/components/others.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-658
Se debe poder configurar un campo con el componente Link.
Se agrego al schema de edit new una nuevo componente de Link con estas propiedades
- label (string, opcional): representa el texto que mostrará el link (valor fijo)
- labelField (string, opcional): representa el nombre del campo de la data que contiene el texto del link
- translateLabels (boolean, opcional): indica si el texto del link es una key de traducción y debe ser procesada.
- target(string, opcional): indica dónde se debe abrir el link al clickear

add component link in edit and new

---

lib/schemas/edit-new/modules/sections/fieldGroup.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-684
Se debe poder indicar un nuevo campo collapsible que indique si el FieldGroup admite ser colapsado o no. No tiene un valor default.
Se agrego al schema de los fieldGroups de los Formularios una nueva prop de collapsible

JMV-684 add collapsible propertie in fieldGroup

---

lib/schemas/edit-new/modules/componentNames.js
lib/schemas/edit-new/modules/components/fieldsArray.js
lib/schemas/edit-new/modules/components/index.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-686
Se debe poder indicar un nuevo componente FieldsArray en formularios. Debe aceptar los siguientes component attributes:
- fields: Un array de Fields. Requerido, al menos un elemento.
- canChangeElements: boolean. Opcional, sin defaults.
- minElements: number. Opcional, sin defaults.
Se agrego un nuevo componente FieldsArray en edit y new. Con las properties descriptas arriba.

Jmv 686 fields array component

---

lib/schemas/browse/modules/components/chips.js
lib/schemas/edit-new/modules/components/chips.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-691
Los campos que tengan el componente UserChip, deben poder aceptar el siguiente component attribute:
- userDataSource: un objeto opcional, que en caso de estar definido, debe tener 4 propiedades obligatorias: firstname, lastname, email e images, de tipo string.
Se agrego al componente de userChip de de los browses y los formularios nuevos componentAttributes.

JMV-691 add properties in user chip

---

lib/schemas/edit-new/modules/headerProperties.js
lib/schemas/edit-new/schema.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-702
Se deben poder definir las siguientes propiedades del schema para customizar el header en Edits:
- header.title.beforeId: Opcional, array de objetos con las siguientes propiedades:
- - name: String, requerido.
- - component: String, requerido. Enum de Componentes que puedan ser ubicados en el header. Al momento, deben ser BadgeLetter y StatusChip.
- header.title.afterId: Exactamente igual que beforeId.
Se agrego al schema default de edit new nuevas properties para agregar componentes en el edit. Con Componentes de listado y sus respectivos componentAttributes.

Jmv 702 header edit new properties

---

lib/schemas/browse/modules/components/actionButtons.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-689
Para los fields que usen el componente ActionButtons, cada acción debe aceptar un nuevo component attribute callback que sea un string, opcional. Debe ser un enum de: removeRow y refresh.
Se agrego al componente de ActionButtons una la property `callback` con un enum de valores en las actions de esta.

JMV-689 add callback in actionButtons

---

lib/schemas/edit-new/modules/sections/apiKeysSection.js
lib/schemas/edit-new/modules/sections/index.js
lib/schemas/edit-new/modules/sectionsNames.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-724
Se debe validar el rootComponent de una sección de edit con el nombre ApiKeysSection
Debe aceptar las siguientes propiedades:
- source: Tipo endpoint. Requerido.
- createEndpoint Tipo endpoint. Requerido.
- deleteEndpoint Tipo endpoint. Requerido.
- parentIdField: Tipo string. Requerido. // Este campo es para poder asociar la API Key a el registro padre (puede ser un usuario, un servicio, o algún otro en el futuro.
Se agrego a las secciones de edit una nueva sección con las properties descriptas arriba.

JMV-724 add apikeys section

---

lib/schemas/edit-new/modules/sections/commonProperties.js
lib/schemas/edit-new/modules/sections/components/topComponents.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-789
Se debe poder declarar position a un topComponent.
Agregar actions a topComponents.
Se agrego al schema de topComponent una nueva prop de position que sea un enum de left y right, opcional. Se agrego actions a topComponents con sus respectivas validaciones

add position propertie in topComponents

---

lib/schemas/common/mapper.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-813
Se debe poder declarar un nuevo mapper para definir un prefijo para traducciones.
Se agrego a los mappers un nuevo mapper llamado prefix con una prop value para definir el prefijo

add prefix mapper

---

lib/schemas/browse/modules/filter-components/select.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-819
Se debe validar un select en los filtros del schema de Browse.
Se agrego al select de los filtros del schema de browse nuevas props para que puedan ser remotas y locales

add validation in select remote browse

---

lib/schemas/browse/modules/filter-components/select.js
lib/schemas/edit-new/modules/components/selects.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-832
Se debe poder definir una propiedad en el schema para los selectores (en filtros, edits y creates) para indicar un prefijo para los labels de los selectores.
Debe validar una propiedad opcional con un valor string
Se agrego al select de los filtros y de EdisCreates una property opcional  labelPrefix

add labelPrefix in selects

---

lib/schemas/edit-new/modules/sections/filesSection.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-835
Se deben poder definir nuevas propeties a la seccion de Files
"fileUploadEndpoint": SOURCE_ENDPOINT,
"fileRelationEndpoint: SOURCE_ENDPOINT
"fileListEndpoint": SOURCE_ENDPOINT,
"fileDeleteEndpoint": SOURCE_ENDPOINT,
"filesTypes": ["STRING"]
Se agregaron los siguientes propeties de la seccion de Files. fileUploadEndpoint es la unica Requerida.

add validations for files section

---

lib/schemas/edit-new/modules/options/remoteOptions.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-844
Se deben agregar tres propiedades opcionales para los selectores (Select y MultiSelect) con opciones remotas:
componentAttributes.options.initialValuesEndpoint de tipo Endpoint
componentAttributes.options.initialValuesFilterNamede tipo string.
componentAttributes.options.initialValuesPathParamde tipo string.
Se agregaron los siguientes properties para los selects remotos del edit create

JMV-844 add new properties in select remote edit create

---

lib/schemas/browse/modules/components/asyncWrapper.js
lib/schemas/browse/modules/components/chips.js
lib/schemas/browse/modules/components/index.js
lib/schemas/edit-new/modules/components/chips.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-839
Se debe agregar la validación para el componente de listados AsyncWrapper en el package de view-schema-validator, según la documentación de https://fizzmod.atlassian.net/wiki/spaces/JMV/pages/594051232/AsyncWrapper 
El endpoint se debe resolver por default.
Se agregaron al los componentes de browse uno nuevo. El asyncWrapperr con las properties definidas en la documentacion. Tambien de la propertie images del UserChip se volvio opcional.

JMV-839 add validation propeties for asyncWrapper

---

lib/schemas/edit-new/modules/sections/filesSection.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-883
Se debe agregar la validación para la seccion de Files.
Se debe agregar un nuevo endpoint para getter el file.
El endpoint se debe resolver por default.
Se agregó a la seccion de FIlesSection una nueva prop
fileGetEndpoint que es un tipo source

add fileGetEndpoint in file section

---

lib/schema-modifier.js
lib/schemas/common/browseBase.js
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json
tests/schema-modifier-test.js

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-883
Se debe aceptar una nueva propiedad opcional canCreate con valor booleano en los listados.
En caso de no estar definida, el valor default debe ser true
En caso de ser false, no se debe insertar la acción por default de New
Se agregó a las properties de browse la nueva prop de canCreate y se modifico el schemaModifier js para que tome en cuenta al meter las actions default cuando canCreate sea true

add prop canCreate in browses

---

lib/schemas/edit-new/schema.js
lib/schemas/new/schema.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-863
Se debe cambiar la validación de los edits para que los targets sean opcionales.
Se saco de requeridos la prop de target en edit y se cambio el schema de new para que solo ahí sea requerido.

add target optional in edits

---

lib/schemas/edit-new/modules/components/fieldsArray.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-871
Se debe definir una nueva propiedad que indique que se maneja un solo campo, y que la data se debe manejar como un array de valores en lugar de array de objetos.
uniqueField: boolean
Se agrego la propiedad uniqueField en el componente de FieldsArray como booleano opcional.

add new prop in fieldsArray

---

lib/schemas/browse/modules/field.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-824
Se debe definir una nueva propiedad que indique si una field de browse se va a ver en desktop o mobile solamente.
deviceDisplay: ["desktop", "mobile"]
Se agrego la propiedad deviceDisplay en el componente de Field de browse con un enum de ["desktop", "mobile"]

add deviceDisplay in browse fields

---

lib/schemas/browse/modules/sortableFields/index.js
lib/schemas/browse/modules/sortableFields/sortableFields.js
lib/schemas/common/browseBase.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-894
Se debe implementar una nueva propiedad para definir los campos ordenables (nombre y dirección inicial), y para definir el orden default (nombre). (similar a lo que se hizo con los filtros)
Se debe seguir validando el ordenamiento tal como estaba anteriormente para dar retrocompatibilidad
Se agregó al schema al schema de browse una nueva propiedad para definir los ordenamientos. En un array de objetos definiendo el name, si es default y su .dirección

add sortable field in browses

---

lib/schemas/edit-new/modules/components/multiInput.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-895
Se debe poder definir una nueva propiedad opcional, que defina un array de nombres de campos que se deben mostrar siempre en un MultiInput. Debe ser un array de strings.
Se agrego al compoenente MultiInput nuevas props, requiredFields que es un array de campos con los nombre de los campos a mostar en el multiInput y se agrego labelPrefix para estandarizar nombres.

add new prop in multi input

---

lib/schemas/browse/modules/components/chips.js
lib/schemas/common/browseBase.js
lib/schemas/common/status-themes.js
lib/schemas/edit/schema.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-896
Se deben poder definir distintos temas en un schema para manejar los colores de los distintos campos en el root del schema,
Estructura de referencia de lo que se necesita:
themes: # Opcional
statusTheme: # Nombre del tema. Objeto de la forma string:string.
new: darkGrey # Mapeo de un valor a su color
readyForPicking: fizzGreen
_default: statusRed # Valor default en caso de no tener el mapeo definido
Se debe validar que la propiedad componentAttributes.useTheme del StatusChip pueda aceptar un boolean o un string (el nombre del tema)
Se agrego al schema de edit y listados la prop de themes para que pueda tener la estructura definida arriba.
Tambien se cambio el valor del tipo …

Jmv 896 status themes

---

lib/schemas/browse/modules/filters/componentNames.js
lib/schemas/browse/modules/filters/components/select-options/remoteOptions.js
lib/schemas/browse/modules/filters/components/select.js
lib/schemas/edit-new/modules/headerProperties.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

Se debe implementar los multiselects en los filtros nuevos del browse
y agregar mappers a los componentes del header de edit
Se agregó al schema del select de los filtros los multiselect y nuevas props para initial values. Se agrego mappper al componente de header de edits.

add multiselect in filters and add mapper in components header edit

---

lib/schemas/edit-new/modules/components/code.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-934
Se debe poder definir una propiedad opcional y booleana para indicar que el componente `Code` es editable.
Se agregó al schema del componente `Code` una nueva prop llamada `canEdit` .

Jmv 927 code component new prop

---

lib/schemas/common/browseBase.js
lib/schemas/common/staticFilters.js
lib/schemas/edit-new/modules/sections/orderItemsSection.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-934
La sección de OrderItems debe aceptar una propiedad `source` de tipo Endpoint, que indique de dónde se deben gettear los productos
En caso de tener esta propiedad también debe aceptar la propiedad `staticFilters` idéntica a la de BrowseSection
También debe aceptar una propiedad `sourceField` de tipo string, que indique en qué propiedad de la data del edit se encuentran los items.
Se agregó al schema de la seccion de OrderItems nuevas propeties para que tenga `source`, `staticFilters` y `sourceField`.
Se refactorizó los staticFilters porque se usa y se va a usar en más lugares.
Ejecutando comando de validacion de package descripto en el …

add new propeerties on section products and refactor staticFilters

---

lib/schemas/edit-new/modules/field.js
lib/schemas/edit-new/modules/triggers/index.js
lib/schemas/edit-new/modules/triggers/triggers.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-967
Se debe validar una nueva propiedad opcional en los campos de formularios: triggers.
Debe ser un array de objetos con la siguiente estructura:
**endpoint**: Endpoint
**endpointParameters**: StaticFilters
**dataMapping**: object<string: string> // key value de mappeo de campos
**triggerOnLoad**: boolean
las propiedades endpoint y dataMapping son requeridas.
Se agregó a los fields de edit/create una nueva propetie `triggers` y se crearon los schemas para estos triggers como se definio en el requerimiento.

add triggers for edit/create fields

---

lib/schemas/browse/modules/filter-components/select.js
lib/schemas/browse/modules/filters/components/select-options/remoteOptions.js
lib/schemas/edit-new/modules/options/remoteOptions.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-968
Se debe modificar el validador de schemas para que admita que la propiedad label del objeto valuesMapper acepte:
a) Un string (comportamiento actual)
b) Un objeto con las siguientes props:
**template**: Un string con el template
**fields**: Un array de fields a utilizar para reemplazar en el template
Se cambio la property label de valuesMapper de los selects de filtros y select de edit/create para que tenga mas tipos de value.

Jmv 968 select remote label template

---

lib/schemas/common/actions/action.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1038
Se debe agregar la validación de endpointParameters como array de StaticFilters, manteniendo la validación vieja también (un objeto key-value) para mantener la retrocompatibilidad.
Se cambio la prop de endpointParameters de las actions para que acepte un nuevo tipo de schemas y tambien se pueda usar el viejo.

add new endpoint parameters in actions

---

lib/schemas/common/browseBase.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1062
Se debe validar una nueva propiedad canExport en todos los listados (páginas o secciones)
Se agrego la prop canExport boolean al schema base de browse

add new prop for browses

---

lib/schemas/browse/modules/filter-components/select.js
lib/schemas/browse/modules/filters/components/select.js
lib/schemas/edit-new/modules/components/selects.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1063
Se debe agregar una propiedad canClear dentro de los componentAttributes de los Selects y Multiselects. Es un booleano, opcional y sin default.
Se agrego una prop a los schemas de los selects y multiselects de los browses y forms.

add new props for selects

---

lib/schemas/browse/modules/components/chips.js
lib/schemas/edit-new/modules/components/chips.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1064
Se debe poder configurar, además de los componentAttributes actuales los siguientes (todos strings opcionales)
- textColor
- backgroundColor
Se agregaron nuevas props al schemas de Chip de Browses y Forms

add new propeties for chip component

---

lib/schemas/edit-new/modules/validations/types/literal.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1065
Se debe validar una nueva propiedad opcional referenceValueType como un enum de static y dynamic en las condiciones de Listados y Formularios.
Estas validaciones se hicicieron en el sprint pasado, asi que hice lo mismo pero para las validaciones literales

add new props for validations

---

lib/schemas/edit-new/modules/headerProperties.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1064
Se debe validar una nueva propiedad opcional identifier. Con dos opciones de configuración:
string representando el nombre de una propiedad de la data del edit
object con las propiedades template y fields. Funciona igual que los labels de los selectores.
Se agrego una nueva prop al schema de componente de header de edit de identifier con las props descriptas arriba.

add header edit new props

---

lib/schemas/edit-new/modules/sections/components/topComponents.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1082
Se deben validar la opción de poner callbacks, igual que se hizo en los ActionButtons de listados.
Los callbacks válidos son _reloadSectionData_ y _refresh_.
Solo aplican a las ActionButtons que sean de tipo endpoint (no a las de tipo link)
Se agregaron nuevas props a los action buttons de los top componets de los edits/create

add action with callback in top sections

---

lib/schemas/edit-new/schema.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json
tests/mocks/schemas/new.yml

https://fizzmod.atlassian.net/browse/JMV-1119
Se debe agregar una nueva propiedad canCreate al schema de edit/create, sea opcional boolean.
Se agrego una nueva prop boolean opcional al schema de edit/create

add canCreate prop in edit create schema

---

lib/schemas/edit-new/modules/componentNames.js
lib/schemas/edit-new/modules/components/index.js
lib/schemas/edit-new/modules/components/selectMultilevel.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1156
Se debe agregar un nuevo schema para un nuevo component en edit/create (SelectMultilevel)
Properties iguales a las del Select remoto
mas unas props nuevas
- parentFilterName(string-required)
- maxLevel(number-optional)
Se agrego un nuevo componente con las mismas props de un Select remoto y  con props adicionales.

validate schemas select multilevel

---

lib/schemas/common/browseBase.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1159
Se debe agregar un nueva prop a los Browses para poder refrescar un listado.
Se agrego una nueva prop de canRefresh en todos los browses, boolean y opcional

add new prop canRefresh in browses

---

lib/schemas/browse/schema.js
lib/schemas/common/browseBase.js
lib/schemas/edit-new/modules/sections/browseSection.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1203
Agregar una nueva prop a los browse para que puedan ser reordenable.
Se agregó una prop nueva al schema de browse llamada sortEndpoint que indique el endpoint para reordenar el listado.

Jmv 1203 reorder browse prop

---

lib/schemas/browse/modules/filters/components/input.js
lib/schemas/browse/modules/filters/components/select.js
lib/schemas/edit-new/modules/components/input.js
lib/schemas/edit-new/modules/components/selects.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1208
Agregar componentAttribute icon como un string opcional en:
Selects y Input de edit/create y en filtros de browse
Se agregaron en los schemas de select y input de edit/create y browse, la prop de icon

add icon prop in selects and input componenets in edit/create and browse

---

lib/schemas/browse/modules/field.js
lib/schemas/browse/modules/interactions.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

https://fizzmod.atlassian.net/browse/JMV-1211
Se debe poder indicar en cada campo de un Listado las interacciones que puede tener con el usuario.
Se debe poder indicar interacciones para el hover y para el click.
Debe ser configurable de manera independiente para Mobile y Desktop (por ejemplo para que en desktop algo pase en el hover, pero en mobile pase en el click)
En cada una se debe poder indicar una de las siguientes opciones de interacción:
- Tooltip (el tooltip negro con un texto)
- ListTooltip (el más grande, blanco con borde azul que muestra un listado de items)
- ListModal (no hace falta mucha aclaración para este)
Cada una de las opciones tiene su propia configuración:
Tooltip
Debe poder recibir un label fijo, o un campo de …

Jmv 1199 fields iteractions

---

lib/schemas/edit-new/modules/sections/section-files/common.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1234
Agregar una nueva prop a los schemas de secciones de archivos.
nueva prop de componentAttributes
- fileSortEndpoint: sourceEnpoint - opctional
Se agrego una nueva prop al schema de las secciones de files

add fielSortEndpoint in files sections

---

lib/schemas/browse/modules/field.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

https://fizzmod.atlassian.net/browse/JMV-1212
Se debe agregar la prop de `appearance`  como lo tiene el browse, pero con las siguientes propiedades:
- Alineación horizontal (**align** - _left_|_center_|_right_)
- Alineación vertical (**verticalAlign** - _top_|_center_|_bottom_)
- Color de fuente (**fontColor** - string) - El color se debe procesar como siempre.
- Tamaño de fuente (**fontSize** - _base_|_baseSmall_|_small_|_xsmall_|_large_|_xlarge_|_xxlarge_)
Se agregó la prop de appearance como lo tiene el browse pero con las propiedades descriptas arriba.

add fields appearance

---

lib/schemas/edit-new/modules/sections/commonProperties.js
lib/schemas/edit-new/schema.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1241
Se debe poder definir una propiedad para colapsar todas las tabs de un edit
Se debe poder definir una propiedad para colapsar/no colapsar una tab específica de un edit
Se agregó una nueva prop a las secciones llamada `collapse` (booleana-opcional) y otra para el schema de edit/create para definir si todas las secciones son collapsables llamada `collapseSections` (booleana-opcional)

add collapse section props

---

lib/schemas/browse/modules/interactions.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1263
Agregar endpointParameters al schema de ListTooltips y ListModal
Se agregó la prop de endpointParameters en el shema de interactions de field de browse

add endpointParamenters for ListTooltip and ListNodal components

---

lib/schemas/common/mapper.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1284
https://fizzmod.atlassian.net/browse/JMV-1294
Agregar prop a mappers de suffix y prefix
- translate: BOOLEAN|OPTIONAL
Agregar mapper de currency con las siguientes props
- currencyCode: STRING|OPTIONAL
-  currencyField: STRING|OPTIONAL
Se agregaron las props a los mappers descriptions arriba. Se hizo un refactor de los mappers para que validen los mapper que son un array de los mismos.

Jmv 1284 and 1294 suffix preffix currency mappers new props

---

lib/custom-schema-validator.js
lib/schemas/edit/schema.js
lib/validator.js
tests/custom-schema-validator.js

https://fizzmod.atlassian.net/browse/JMV-1292
Se debe empezar a validar el campo source de los Edits como opcional sólo cuando no haya un MainForm en el schema.
Se saco de la prop source de requeridos, y se hizo una clase que se ejecuta luego de la validacion de schema para verificar si se debe requerir o no esta prop.

JMV-1292 add edit custom validations

---

lib/schemas/browse/modules/components/asyncWrapper.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

https://fizzmod.atlassian.net/browse/JMV-1296
Se deben agregar las siguientes nuevas props al schema de AsyncWrapper de browse
```
dataMatching: (object|optional|min2props)
local: (STRING|require)
remote: (STRING|require)
targetField: (STRING|OPTIONAL)
```
Se agregaron las props al schema del AsyncWrapper del browse

add async wrapper brows new props

---

lib/schemas/common/browseBase.js
lib/schemas/common/graphs.js
lib/schemas/dashboard/schema.js
lib/schemas/index.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/dashboard.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/dashboard.json
tests/validator-test.js

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1334
Se deberá crear un tipo de schema nuevo
Deberá reutilizar la prop de filters de los browses
Deberá contener una prop graphs (validar nombre) como requerido, y debe contener al menos 1 gráfico
Los gráficos deberán tener como requeridas las siguientes properties:
component: tipo de gráfico (columnChart, Table)(required)
filters: Deberá reutilizar la prop de filters de los browses(optional)
name: identificador string(required)
title: titulo de char(optional)
subtitile: subtitulo de charts(optional)
source: SourceEndpoint (required)
endpointParameters: statisFilters-endpointparamters (optional)
componentAttributes: objeto con opciones de graficos (optional)
x: donde empieza en el eje X - (required)
y: …

Jmv 1334 schema dashboard and new props for browse

---

lib/schemas/edit-new/modules/sections/commonProperties.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1341
Se debe agregar una nueva prop a las secciones de edit para indicar de que secciones de form incluir data, para validaciones y componentes de topComponents
Se agrego la prop includeDataFrom en seccines como array de string que indique las secciones de form a incluir en la data utlizada por los TopComponents

add new prop for include data from others sections

---

lib/schemas/edit/schema.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1381
Agregar  prop "remoteActions" al schema de edit/create
Opcionalmente se podrá pasar un titulo para el popup
Deberá ser un objeto con un source y sourceEndpointParameters
Se agregue la props remoteActions que es un objeto opcional con source , sourceEndpointParameters, titile y translateTitle

JMV-1381 add remoteActions properties

---

lib/schemas/browse/modules/filters/components/dateTimePicker.js
lib/schemas/edit-new/modules/components/dateTimePicker.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1373
Se deberá agregar dos props nuevas, en el componente de DateTimePicker 
La prop setStartOfDay (boolean|opcional) 
la prop setEndOfDay(boolean|opcional)
Se agregaron las nuevas props a los componentes de DateTimePicker existentes

JMV-1373 add dateTimepicker new props

---

lib/schemas/edit-new/modules/field.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1463
Se deberá agregar una nueva prop opcional llamada defaultValue
Se deberá poder usar en todos los componentes: 
Se agregó una nueva prop a los Fields de Forms, de todos los tipos de datos

add default value prop in field form

---

lib/schemas/edit-new/modules/triggers/triggers.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1613
Se debe agregar al schema de triggers una nueva props llamada componentMapping.
Se agrego al schema de triggers una nueva props llamada componentMapping, y se saco de requerido dataMappding para que sea opcional

JMV-1613 add schema props for triggers

---

lib/schemas/edit-new/modules/componentNames.js
lib/schemas/edit-new/modules/components/index.js
lib/schemas/edit-new/modules/components/preview.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1605
Se debe crear un nuevo componente de edit/create con el nombre de Preview.
El componente deberá ser lo suficientemente configurable como para mostrar las siguientes cosas:
Imagen
Titulo (nombre del producto)
Subtitulo 
Descripción (doble linea) 
Precio (label y doble value)
Se creó un nuevo componente Preview configurable con distintas props descriptas en el ticket.

JMV-1605 add preview component

---

lib/schemas/browse/modules/components/link.js
lib/schemas/edit-new/modules/components/link.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-1684
Se deberá agregar una nueva prop de componentAttributes a los componentes de Link
- path: string
Se agregó la nueva prop a los schemas de los componentes Link

add new prop for link component path

---

lib/schemas/common/browseBase.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

Se deberá agregar al schema de los  browses una nueva prop para definir un el nombre de un campo a tomar para interpolar en la url de sortEndpoint.

add new props for sort endpoint field param

---

lib/schemas/browse/schema.js
lib/schemas/common/browseBase.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1711
Se deberá agregar la property *canImport* en el schema del browse
Se agregó una nueva prop al schema de la pagina de browse.

JMV-1711 add canImport  prop

---

lib/schemas/browse/modules/field-appearance.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

https://fizzmod.atlassian.net/browse/JMV-1774
El validador debe permitir los siguientes tipos de valores para width (en appearance):
number - se seguirán aplicando como porcentaje para mantener la retrocompatibilidad
string - puede ser "auto”, un valor en px ("30px”), o un valor en % (“100%”)
Se cambio el schema de la prop de width de appearance de los fields de browse.

change prop witdh in appearace

---

lib/schemas/common/browseBase.js
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1769
Se debe cambiar el nombre a la prop hasPreview por canPreview en los browses
Se cambió el nombre a la prop hasPreview por canPreview.

change hasPreview for canPreview

---

lib/schemas/browse/modules/field-appearance.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json

https://fizzmod.atlassian.net/browse/JMV-1757
Se debe agregar medium a los valores posibles para fontSize en los appearance de los fields de browse.
Se agrego al schema appearance de los fields de browse una nueva opcion para fontSize

add appearance new font size

---

lib/schemas/browse/modules/filters/components/dateTimePicker.js
lib/schemas/edit-new/modules/components/dateTimePicker.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1801
Se deberá agregar al DateTimePicker la prop opcional format para definir la string con el formato con el que debe enviarse la data. 
Se agrego al schema de los dateTimePicker una nueva prop llamada format tipo string

add new prop for dateTimePicker

---

lib/schemas/browse/modules/filters/components/select.js
lib/schemas/edit-new/modules/components/selects.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1803
Se deberá agregar una nueva prop preloadOptions (boolean) para poder traer las opciones remotas antes de abrir el Select .
Se agrego al schema de los selects una nueva props llamada preloadOptions tipo boolean

add preload options select prop

---

lib/schemas/edit-new/modules/sections/formSection.js
lib/schemas/edit-new/modules/sections/mainForm.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1915
Se deberán agregar dos nuevas properties para ocultar información de usuario creador y modificados de los form sections.
Las properties deberán ser:
- hideUserCreated (boolean)
- hideUserModified (boolean)
Se agregaron las dos nuevas props a los schemas de las secciones de mainForm y formSection

add new props for form sections

---

lib/schemas/edit-new/modules/components/asyncWrapper.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1941
Agregar prop targetField(string) al schema de AsyncWrapper de forms
Se agrego al schema de asyncWrapper de forms una nueva prop targetField, y se refactorizo un poco para su mejor funcionamiento.

add asyncwrapper form new prop

---

lib/schemas/browse/schema.js
lib/schemas/common/topComponents.js
lib/schemas/edit-new/modules/sections/commonProperties.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse-not-actions.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-1943
Se deberá implementar la funcionalidad de los topComponents tanto en el browse como en el browseSection
Se agrego a los browses en general una nueva prop de topComponents, se hizo un pequeño refactor de topComponents para su mejor uso. Se agrego un callback nuevo para las acciones en un browse ('reloadBrowse')

add topComponents in browse page

---

lib/schemas/edit-new/modules/componentNames.js
lib/schemas/edit-new/modules/components/index.js
lib/schemas/edit-new/modules/components/location.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-2065
Se debe agregar componente Location para que tenga en componentAttributes lo siguiente
- label:  requerido (string|object)
- - Con label tipo string traducible o tipo template(object)
- fieldsMapping: opcional (object)
- - latitude : requerido (string)
- - longitude requerido (string)
Se agrego el nuevo componente a los Forms y para los fieldGroup en general que usan summary

Jmv 2065 location component

---

lib/schemas/browse/modules/components/link.js
lib/schemas/edit-new/modules/components/link.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json
tests/mocks/schemas/expected/preview.json
tests/mocks/schemas/preview.yml

https://fizzmod.atlassian.net/browse/JMV-2216
Se debe agregar a los componentAttributes del componente Link la compatibilidad con la nueva prop labelMapper (que funciona igual que la prop mapper).
Se agregó la prop de labelMapper a los componentes de Link.

add labelMapper for Links

---

lib/schemas/edit-new/modules/headerProperties.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-2221
Se debe agregar un nuevo componente para el header de edit/preview.
Se agregó a los componentes de header de edit/preview un nuevo componente `DefaultTitle` al que se le puede pasar por componenentAttrbutes la prop de `identifier`.

add defaultTitle header component

---

lib/schemas/browse/modules/field.js
lib/schemas/edit-new/modules/field.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-2271
Se deberá generar una nueva property en los fields para evitar que se traduzcan los labels de los mismos
La property se deberá llamar transalateLabels: true/false
- El default deberá seguir siendo true
Se agregó la prop translateLabels en los fields de browse, form y demás sections.

add translateLabel prop in fields

---

lib/schemas/browse/modules/filters/components/select.js
lib/schemas/browse/modules/filters/components/userSelector.js
lib/schemas/edit-new/modules/components/iconSelector.js
lib/schemas/edit-new/modules/components/userSelector.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-2291
Se deberá agregar la property canClear en los siguientes componentes:
- IconSelector
- UserSelector
- SelectMultiLevel => en este caso solo deberá considerar esta prop en el primer nivel
Se agregó la prop canClear a los selector definidos en la descripcion

add canClear prop to some selectors

---

lib/schemas/browse/modules/filters/components/select.js
lib/schemas/common-sections/sections/components/fieldGroup.js
lib/schemas/common-sections/sections/formSection.js
lib/schemas/common-sections/sections/mainForm.js
lib/schemas/common-sections/sections/readOnlySection.js
lib/schemas/edit-new/modules/components/selects.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json
tests/mocks/schemas/expected/preview.json
tests/mocks/schemas/preview.yml

Se deben agregar las siguientes properties:
En los schemas de `MainForm`, `ReadOnlySection` y los `FormSections`
agregar las siguiente prop
- columnsType: [ default , even ]
A los selects remotos de forms y filtros agregar las siguiente property en los componentAttributes
- responseProperty(string)
A los fieldGroups se le agrego la siguiente property
- translateLabel(boolean)
Se agregaron las siguientes properties a

add new propertys for schema

---

lib/schemas/common/actionCallbacks.js
lib/schemas/monitor/cards/BaseCard.js
lib/schemas/monitor/cards/actions.js
tests/mocks/schemas/expected/monitor.json
tests/mocks/schemas/monitor.yml

https://fizzmod.atlassian.net/browse/JMV-2463
Se debe agregar el schema para las acciones de las cards de monitor agregandole condicionales.
Se agregó el schema simil remoteActions al schema de cards de monitor, agregandole condicionales a las actions.

JMV-2463 add schema action monitor cards

---

lib/schemas/monitor/schema.js
tests/mocks/schemas/expected/monitor.json
tests/mocks/schemas/monitor.yml

**https://fizzmod.atlassian.net/browse/JMV-2469**
Se deberá poder pasarle una property al monitor para poder definir el tiempo del autoRefresh
Se deberá aceptar un valor numérico
Dicho valor deberá representar segundos
Se deberá tomar como valor minimo 60 segundos
Se cambió el schema de autoRefresh de monitor de boolean a number con el minimo de 60

change autoRefresh monitor property

---

lib/schemas/browse/schema.js
lib/schemas/common/browseBase/browseBase.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

**https://fizzmod.atlassian.net/browse/JMV-2492**
La property canExport y canImport deben estar en los browseSection.
Se cambió el schema de browseBase para que tenga tanto canExport como canImport, para que lo tengan todos los browseSection

move canImport in browse base schema

---

lib/schemas/common/stringPrefix.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

**https://fizzmod.atlassian.net/browse/JMV-2503**
Se deberá modificar el validador para poder usar un prefix que comience con views.
Se deberá validar y restringir que solo se pueda crear hasta un maximo de 2 niveles
Ya que el 3ro va hacer el del propio field
Se cambiò el regex del schema de stringPrefix para que pueda tener prefijos y key traducciones hasta 2 niveles

changes in stringPrefix regex

---

lib/schemas/browse/modules/filters/components/dateTimePicker.js
lib/schemas/edit-new/modules/components/dateTimePicker.js
lib/schemas/edit-new/modules/components/newDatePicker.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

**https://fizzmod.atlassian.net/browse/JMV-2554**
Se deberá poder enviar una nueva property para evitar el uso del timezone
- useTimezone: true/fase
El default deberá ser true
Se agregó una nueva property useTimezone boolean al los schemas de los componentes de DateTimePicker y NewDatePicker

add useTimezone prop in dateTimePicker

---

lib/schemas/common/browseBase/massiveActions.js

Se tiene que sacar el required de la prop source, de massiveActions.

massive actions remove prop required

---

lib/schemas/edit-new/modules/components/location.js
lib/schemas/edit-new/modules/components/map.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-2568
Dentro de componentAttributes se definiran propiedades para customizar el marcador de los mapas
property `markers.icon`
Se deberá poder usar los iconos de la font de janis
En caso de no definirlo, se deberá usar el marker default de janis de la siguiente [forma](https://fizzmod.invisionapp.com/d/main#/console/16040058/440394270/preview)
property `markers.color` en donde se podrá definir alguno los colores posibles de la font de janis
En caso de no definirlo, se usara el color gris (normal).
propiedades useTheme, themeConditionals  las cuales deben funcionar igual  que el StatusChip
property markerInfo en donde se deberá poder definir las siguientes properties (simil card de monitores): …

Jmv 2568 map location new props

---

lib/schemas/edit-new/modules/components/fieldsArray.js
lib/schemas/edit-new/modules/field.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-2603
Se deberá poder definir en los componentes ( **input** / **select**) si usa el el label normal o floating
**floatingLabel**: true (el default es false)
Se deberá poder pasarle una property a para poder eliminar el divisor entre los elementos
La idea es que las opciones se vean más juntas y que se entienda que son parte de los mismo
Se deberá revisar el margin del ultimo input que tiene un width
Se deberá poder setear la propiedad **addButtonText** vacía (false || '') y que no muestre un espacio
Se deberá agregar una property **addButtonPosition** con los valores left / right, en donde left deberá ser el default.
Actualizar la documentación con las nuevas props. …

JMV-2603 - add new props for fieldsArray and add new prop in field form

---

lib/schemas/browse/modules/filters/components/dateTimePicker.js
lib/schemas/common-sections/sections/remoteSection.js
lib/schemas/common/browseBase/massiveActions.js
lib/schemas/edit-new/modules/components/dateTimePicker.js
lib/schemas/edit-new/modules/components/multiInput.js
lib/schemas/edit-new/modules/components/newDatePicker.js
lib/schemas/monitor/schema.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

https://fizzmod.atlassian.net/browse/JMV-2659
Se deberá poder definir los rangos de valores de los horarios **timeOptions**:
Cada x hs => **hourLapse**
Cada x minutos => **minuteLapse**
Custom: => **custom**
- 14:00
- 16:00
- 18:00
No se puede ingresar un horario especifico
La idea es que si o si tengan que seleccionar del listado, cosa que si la config es Cada 1 hr, no puedan poner 14:32
La property se deberá llamar: **canCreateTime**
Se agregaron las properties descriptas arriba a los Componentes de dateTimePicker

add new props for dateTimePicker

---

lib/schemas/common/browseBase/massiveActions.js
lib/schemas/common/generic-actions/action.js
lib/schemas/common/modalSize.js
lib/schemas/common/topComponents.js
lib/schemas/definitions/index.js
lib/schemas/edit-new/modules/components/location.js
lib/schemas/edit/schema.js
lib/schemas/monitor/schema.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json
tests/mocks/schemas/expected/monitor.json
tests/mocks/schemas/monitor.yml

https://fizzmod.atlassian.net/browse/JMV-2658
Se deberá agregar una property en los componentes que utilicen un popup para poder determinar el size:
- small
- medium
- large
- extra-large
- mobile
Se le debe agregar al los schemas de: Location, RemoteActions de edit, MassiveActions de browse, a las acciones de monitor,  Al ActionForm de topComponents y al action type form de genericActions
Se agregaron las properties de `modalSize` a los componentes mencionados arriba.
Al componente de actions de monitor se agregó al baseCard la prop de `actionsModalSize`

add modalSize in diferent components and schema

---

lib/schemas/monitor/schema.js
tests/mocks/schemas/expected/monitor.json
tests/mocks/schemas/monitor.yml

https://fizzmod.atlassian.net/browse/JMV-2688
Se deberán poder agregar mappers a cada columna de monitor.
Se agregó la property `mapper` para las columnas de monitores.

add mapper for monitor columns

---

lib/schemas/common/browseBase/browseBase.js
lib/schemas/common/featureFlags.js
lib/schemas/definitions/index.js
lib/schemas/monitor/schema.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/monitor.json
tests/mocks/schemas/monitor.yml

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-2589
Agregaría una setting al root del schema featureFlags.allowMultiSort: true/false
Se agregó la property featureFlags.allowMultiSort en los schemas de browse y monitores

add new props featureFlags

---

lib/schemas/browse/modules/filters/components/select-options/localOptions.js
lib/schemas/browse/modules/filters/components/select-options/remoteOptions.js
lib/schemas/browse/modules/filters/components/select.js
lib/schemas/edit-new/modules/components/selects.js
lib/schemas/edit-new/modules/options/localOptions.js
lib/schemas/edit-new/modules/options/remoteOptions.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit.json

LINK AL TICKET
https://fizzmod.atlassian.net/browse/JMV-2670
Se deberá poder definir entre de las opciones locales, un grupo al cual pertenecen
Se deberá poder definir dentre las opciones remotas, de que field tomar el “grupo”
Se deberá poder definir si dicho nombre del grupo es traducible o no
Se deberá documentar las nuevas properties
Se agrego la nueva props, en los filtros y en los selects

add props in selects

---

lib/schemas/monitor/schema.js
tests/mocks/schemas/expected/monitor.json
tests/mocks/schemas/monitor.yml

https://fizzmod.atlassian.net/browse/JMV-2695
Se deberá mover la estructura de source y endpointParameters a cada columna
Se deberá desestimar el source y endpointParameters del route del schema
Tener en cuenta el validador
Se deberá implementar el load more en cada columna
Deberá tener el mismo funcionamiento que el actual, pero por cada columna, en caso de que existan más registros
Dicho botón de load more, solo deberá ejecutar la request de cada columna
Evitar que el load more ejecute el skeleton
Se pasó el source y endpointParameters del root del schema a cada fields, es decir para cada columna

change schema monitor

---

lib/schemas/common/graphs.js
tests/mocks/schemas/dashboard.yml
tests/mocks/schemas/expected/dashboard.json

- https://janiscommerce.atlassian.net/browse/JMV-2840
- Se creo un componente provisorio para poder contar con una Card la cual puede mostrar un Titulo, valor y porcentaje en los dashboard de KPI. El problema es que estabamos usando el schema de un graph donde se requiere tener declarado un source y en el caso que se quiera mostrar el componente TextCardKPI y solo un titulo, no era necesario tener un source declarado
- Por medio de condicionales, se definio que si el componente es TExtCardKpi, se agregue las properties value y percent y ademas se modifica la key required para eliminar source. 
- Tener en cuenta que esto es provisorio. Al momento de hacer el refactor de todo el dashboard vamos a volver para atras con estos cambios.
- corriendo los test. Agrege dos TextCardKpi, uno con …

add conditional properties for custom textCardKpi graph

---

lib/schemas/browse/modules/filters/filters.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse.json

- https://janiscommerce.atlassian.net/browse/JMV-2791
- Se requiere poder definir en ciertas vistas filtros como requerido obligando al usuario a usar algunos de ellos para poder mostrar informacion
- Se agrego la prop required con tipo boolean
- corriendo los test, agregue en el browse el filtro filterInput la prop required en true
-
-
```
- key required in filter schema
- 
- 
- 
- 
```

add prop required in filter schema

---

lib/schemas/preview/sectionsNames.js
tests/mocks/schemas/expected/preview.json
tests/mocks/schemas/preview.yml

https://janiscommerce.atlassian.net/browse/JMV-2359
Se requiere agregar la seccion RemoteSection a preview para poder utilizarla por schemas
Se agrego el tipo de seccion RemoteSection a previews
Corriendo los test donde ya esta agregado el RemoteSection
-
-
Agregado RemoteSection a secciones de preview
Agregado RemoteSection a secciones de preview
- 
- 
- 
- 
```

Agregado RemoteSection to Preview Sections

---

lib/deprecation-validators/index.js
lib/deprecation-validators/remoteActions-deprecation.js
lib/schemas/common/actions.js
lib/schemas/common/remoteActions.js
lib/schemas/edit/schema.js
tests/mocks/schemas/edit-with-actions-source.yml
tests/mocks/schemas/edit-with-actions-static.yml
tests/mocks/schemas/edit-with-actions.yml
tests/mocks/schemas/edit-with-remote-actions.yml
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit-with-actions-source.json
tests/mocks/schemas/expected/edit-with-actions-static.json
tests/mocks/schemas/expected/edit-with-actions.json
tests/mocks/schemas/expected/edit-with-remote-actions.json
tests/mocks/schemas/expected/edit.json
tests/validator-test.js

… remoteActions no ambos
- [Link](https://janiscommerce.atlassian.net/browse/JMV-2958)
- Se necesita crear una nueva prop Actions que reemplace pero no elimine las RemoteActions. 
- Se agrego un nuevo schema para **Actions** que reutiliza la logica de **massiveActions** para que tome tanto valores **static** como **remote** los cuales llegan asi: static; **StaticActions**, remote; **Source**. 
- Se agrego validacion para que sea requerido uno de estos dos tipos ya sea **static** o **remote** para esto se utilizo **anyOf** que valida que cualquiera de las dos properties sean requeridas pudiendo ser 1 de las 2 o ambas. 
- Se extrajo el schema de **remoteActions** en un archivo nuevo para poder reutilizarlo en el condicional agregado, dichos condicional valida si existe **actions** y cuando …

Agregado actions a Edit

---

lib/deprecation-validators/index.js

https://janiscommerce.atlassian.net/jira/software/c/projects/JMV/boards/445?modal=detail&assignee=63da4463c2b1cb6b3470270d
Remover el mensaje de deprecacion de remoteActions
Se comento el import que accede al archivo que contiene la funcion validadora y que genera el warning de deprecation
Ejecutando el siguiente comando para verificar que no se muestra el warning
`node index.js validate -i tests/mocks/schemas/edit-with-remote-actions.yml `
-
-
```Se desactivo el warning de depracacion de remoteActions
- 
- Se desactivo el warning de depracacion de remoteActions
- 
- 
- 
```

Removido warning de deprecacion de remoteActions

---

.github/workflows/coverage-status.yml
lib/schemas/edit-new/modules/components/map.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://janiscommerce.atlassian.net/browse/JMV-3070
Contexto
En el detalle de una ruta, estamos mostrando un mapa con el recorrido hecho por el driver donde se entregaron los distintos pedidos. Esto es gracias a la App de delivery donde se hizo un desarrollo donde le enviamos el recorrido del chofer cada X tiempo para despues dibujar todo el recorrido. Janis guarda esta informacion para luego mostrarla en el mapa.
El problema es que en cada latitud y longitud que se usa para dibujar todo el camino recorrido, se esta mostrando un marcador que no brinda ninguna funcionalidad y al contrario, esta molestando.
Necesidad
Poder mostrar solamente un marcador para el punto de origen y otro para el de destino.
Se agrego la prop `hideDefaultMarkers` al componente `map.js` y a los test `edit.yml` y …

add marker prop: hideDefaultMarkers

---

lib/schemas/common/mapper.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://janiscommerce.atlassian.net/browse/JMV-3082
https://janiscommerce.atlassian.net/browse/JMV-3084
Se debe agregar un nuevo mapper para poder setear valores estáticos en un campo readOnly, donde tenga la posibilidad de traducirlo.
_**Analisis funcional**_
Agregar un mapper nuevo addStaticValue, donde podamos mandarle por props un value(string) y una property que indique sise traduce o no(Boolean).
El campo que tenga este mapper, solo va mostrar el valor que este genere.
Se agregó el nuevo mapper addStaticValue con las properties descritas en el requerimiento
- Accediendo a la rama y ejecutando npm run test para verificar que los test pasan correctamente, tambien probando las properties del nuevo mapper en un schema.
- https://janiscommerce.atlassian.net/wiki/spaces/JMV/pages/221967166 …

add addStaticValue mapper

---

lib/schemas/edit-new/modules/components/input.js
tests/mocks/schemas/edit-with-min-max-input.yml
tests/mocks/schemas/expected/edit-with-min-max-input.json
tests/mocks/schemas/new-with-min-max-input.yml
tests/validator-test.js

https://janiscommerce.atlassian.net/browse/JMV-3060
Se requiere agregar las props minValue, minValueField, maxValue y maxValueField a los componentAttributes de Input para poder utilizarlo en todo views, se debe condicionar que solo se pueda agregar minValue o minValueField y solo maxValue o maxValueField, tambien debe permitirse no incluir ninguna de las 4.
Se agregaron properties al schema de componentAttributes de Input atraves de makeComponent, tambien se le paso a makeComponent condicionales que limitan el uso del valor estatico y dinamico dejando usar solo uno para min y solo uno para max, se agregaron casos de prueba para probar la funcionalidad nueva en edit y new.
Se agregaron tambien condicionales para limitar que solo se pueda usar cualquiera de las props nuevas cuando type sea …

Agregado min max fields estaticos y dinamicos a input

---

lib/schemas/common-components/link.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse.json

https://janiscommerce.atlassian.net/browse/JMV-3121
Se requiere agregar la key openPrint a los componentAttributes de Link para poder indicar a views que el Link abrira una tab y un dialogo de impresion
Se agrego la key openPrint a los componentAttributes de Link
Se agrego un caso de prueba con la key nueva en browse
Ingresando a la rama y corriendo `npm run test` para probar que no rompa, se puede agregar la key en otros componente Link y no debe romper
-
-
```Agregada key openPrint en componentAttributes de Link
Agregado caso de prueba con la key nueva en browse
- Agregada key openPrint en componentAttributes de Link
- Agregado caso de prueba con la key nueva en browse
- 
- 
- 
- 
```

Agregada key openPrint componentAttributes a Link

---

lib/schemas/edit-new/modules/components/selectMultilevel.js
tests/mocks/schemas/edit-with-actions-source.yml
tests/mocks/schemas/expected/edit-with-actions-source.json

https://janiscommerce.atlassian.net/browse/JMV-3152
Se requiere agregar la prop `parentFilterDefaultValue` para poder agregar un valor por defecto por el cual se filtraran `SelectMultiLevel` cuando no aun no se haya seleccionando ningun valor. Dicho valor puede ser string, number o boolean ya que debe poder ser definido como lo requiera back
Se agrego la prop `parentFilterDefaultValue` al validador de `SelectMultiLevel` y se agrego la prop a tests para comprobar su funcionamiento
Ejecutando el comando npm run test y validando que no rompa nada. Se puede quitar la prop y tanto del yml como del json para comprobar que es una prop opcional. Tambien debe poder recibir valores string, number y boolean
-
-
```Agregada prop `parentFilterDefaultValue` al validador de `SelectMultiLevel`
- Agregada …
```

Agregada prop parentFilterDefaultValue

---

lib/schemas/edit-new/modules/components/map.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://janiscommerce.atlassian.net/browse/JMV-3210
Cambiar el validador y en vez de string, usar un bool pero eso solo te va a permitir usar el marcador por default.
Cambiamos la prop para que ya no acepte string, sino boolean. Para cuando se quiere usar el marcador por default. En caso de querer personalizarlo se seguira optando por el objeto con sus props.
- Correr los test.
- Verificar que las dos nuevas props solo acepten: boolean o un objeto con icono como requerido (size y color opcional).
- Sin icon el objeto, deberia romper.
- Si recibimos un string debería romper
- Si no enviamos las props no debería pasar nada, seguiría funcionando los test.
- Si recibimos el objeto con prop icon en las nuevas props, pasa tests
https://janiscommerce.atlassian.net/wiki/spaces/JMV/pages/2243166317 …

change type to boolean

---

lib/schemas/browse/modules/filters/components/userSelector.js
lib/schemas/edit-new/modules/components/userSelector.js
tests/mocks/schemas/browse-columnSortableMatch.json
tests/mocks/schemas/expected/browse-columnSortableMatch.json

https://janiscommerce.atlassian.net/browse/JMV-3248
A raiz de ATR-1081: Listar en Ronda sólo Pickers asignados al warehouse
EN PROGRESO
hoy lo que sucede con el UserSelector es que uno de los usos es para poder listar pickers. El problema es que como esta hecho, no acepta endpointParameters y se necesitan para poder agregar distintos filtros, uno de ellos seria el filtro nuevo de pickingpoint. Esto tiene una relacion con lo que se va a hacer en JMV-3247:
Necesidad
Que el componente User selector pueda aceptar endpointParameters
Se agrego la posibilidad de usar endpointParameters en el componente userSelector
Correr los test:
- Que funcionen con endpointParameters definidos.
- Que funcionen sin endpointParameters definidos.
-
-
```
- 
- 
- 
- 
- 
```

add endpointParameters to UserSelector

---

lib/schemas/common/generic-actions/action.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/expected/browse.json

https://janiscommerce.atlassian.net/browse/JMV-1923
Agregar nueva prop para poder renombrar las keys a enviar en la data
Sumamos la prop `requestFields` a las acciones de tipo `form` y `endpoint`
- En el schema de browse se agrego una accion tipo form y endpoint, con la nueva key, podemos probar borrarla y que todo siga funcionando, tambien agregar en otro schema de browse un accion tipo form con la key y que no rompa.
Correr:
npm t
npm run test-file "ruta del archivo"

add requestFields to actions type form

---

lib/schemas/edit-new/modules/components/checkList.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

- https://janiscommerce.atlassian.net/browse/JMV-3302
- Se necesita enviar el valor true por default desde Schema validator a las keys de traduccion del checklist
- Se implemento el valor por default para las keys de traducciones en checklist.js
- Se agregó el valor true en el expected json para que coincida con el esperado que es true
- Levantando la rama y ejecutando npm run test,
- Este test se ejecuta en los edit yml y json, en el caso de YML, si no se envía la key, tomara el valor true, pero tener en cuenta que hay que enviarle true en el esperado
- Si queremos darle valor string o false, se debe agregar al YML la key con el valor y tmb en el JSON
- https://janiscommerce.atlassian.net/wiki/spaces/JMV/pages/2242707533/CheckList#Traducciones
```
- Default value to translate keys
```

add default value to translation keys

---

lib/schemas/index.js
lib/schemas/planning/schema.js
tests/mocks/schemas/expected/planning.json
tests/mocks/schemas/planning.yml
tests/validator-test.js

- https://janiscommerce.atlassian.net/browse/JMV-3454
- Se necesita agregar la vista de `planning` al schema validator
- Se agregó `planning` y sus `schemas` y test para probar
- Las props `root`, `name` y `service` son requeridas
- El `additionalProperties` esta en false por lo que no se deben poder agregar mas props
- Ingresando a la rama,
- En todos los casos, para probar todos los test, ejecutar `npm run test`
Para probara individualmente los cambios, ejecutamos
yml: `node index.js validate -i tests/mocks/schemas/planning.yml`
json: `node index.js validate -i tests/mocks/schemas/expected/planning.json`
Probar sacando y poniendo props
```
- Planning schema
- Planning test cases 
```

add planning to validator

---

lib/schemas/monitor/cards/CapacitySlotCard.js
lib/schemas/monitor/cards/cardNames.js
lib/schemas/monitor/cards/index.js
tests/mocks/schemas/expected/monitor.json
tests/mocks/schemas/monitor.yml

- https://janiscommerce.atlassian.net/browse/JMV-3484
- Se necesita contar con el uso de la nueva card `CapacitySlotCard` por schema ya validada desde el validadador
- Se creó la `card` con todo lo mismo que la **BaseCard** solo se le quitó el `fieldsGroup`
- Se agregó el caso de la nueva card en los **json** y **yml** de monitor
- Ingresando a la rama,
- En todos los casos, para probar todos los test, ejecutar `npm run test`
Para probara individualmente los cambios, ejecutamos
**yml**: `node index.js validate -i tests/mocks/schemas/monitor.yml`
**json**: `node index.js validate -i tests/mocks/schemas/expected/monitor.json`
Probar sacando y poniendo props, no debería dejar que ponga ninguna, por ejemplo no acepta `fieldsGroup`
```
- New card in Monitor
- Monitor json and Yml
```

add CapacitySlotCard to monitor valid fields

---

lib/schemas/edit-new/modules/components/checkList.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

- https://janiscommerce.atlassian.net/browse/JMV-3416
- Agregar al validador del `checklist`, la posibilidad de enviarle `endpointParameters`
- Se agregó la definición del `endpointParameters` al componente, el mismo no es requerido
- Se agregó un ejemplo en los schemas (**ChecklistThree**) en el que se le pasan los `endpointParameters`
- Ingresando a la rama,
- En todos los casos, para probar todos los test, ejecutar `npm run test`
Para probara individualmente los cambios, ejecutamos
**yml**: `node index.js validate -i tests/mocks/schemas/edit.yml`
**json**: `node index.js validate -i tests/mocks/schemas/expected/edit.json`
- [Checklist](https://janiscommerce.atlassian.net/wiki/spaces/JMV/pages/2242707533/CheckList)
```
- EndpointParameters in Checklist component
```

add endpointParameters to checklist

---

lib/schemas/monitor/schema.js
tests/mocks/schemas/expected/monitor.json
tests/mocks/schemas/monitor.yml

https://janiscommerce.atlassian.net/browse/JMV-3508
- Se debe agregar la key `columnLink` dentro del schema del monitor para que el back la pueda utilizar
- Se agregó la key mencionada dentro de _lib/schemas/monitor/schema.js_
- Ingresar a la branch, correr los tests (se podría agregar la nueva como key como required para verificar que los tests no pasan si no se agrega la misma)
yml: `node index.js validate -i tests/mocks/schemas/monitor.yml`
json: `node index.js validate -i tests/mocks/schemas/expected/monitor.json`
```
- columnLink key in monitor schema
```

JMV-3509-implementar-link-por-cada-columa

---

lib/schemas/monitor/schema.js
tests/mocks/schemas/expected/monitor.json
tests/mocks/schemas/monitor.yml

https://janiscommerce.atlassian.net/browse/JMV-3510
- Se deben agregar la key `columnsWidth` y `columnsQuantityScroll` dentro del schema del monitor para que el back la pueda utilizar
- Se agregaron las keys mencionada dentro de _lib/schemas/monitor/schema.js_
Ingresar a la branch, correr los tests:
`yml: node index.js validate -i tests/mocks/schemas/monitor.yml`
`json: node index.js validate -i tests/mocks/schemas/expected/monitor.json`
Revisar que los test corran correctamente
```
- columnsWidth & columnsQuantityScroll keys in monitor schema root
```

JMV-3511-modificar-tamaño-de-card

---

lib/schemas/edit-new/modules/components/code.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

- https://janiscommerce.atlassian.net/browse/JMV-3534
- Agregar al validador del `Code`, la posibilidad de enviarle `canCopy`
- Se agregó la definición del booleano `canCopy` al componente
- Se agregó el caso en los test del edit
- Ingresando a la rama,
- En todos los casos, para probar todos los test, ejecutar `npm run test`
Para probara individualmente los cambios, ejecutamos
**yml**: `node index.js validate -i tests/mocks/schemas/edit.yml`
**json**: `node index.js validate -i tests/mocks/schemas/expected/edit.json`
- [Code](https://janiscommerce.atlassian.net/wiki/spaces/JMV/pages/2242773030/Code)
```
- canCopy to Code component
```

add canCopy prop on code component

---

lib/schemas/monitor/schema.js
tests/mocks/schemas/expected/monitor.json
tests/mocks/schemas/monitor.yml

https://janiscommerce.atlassian.net/browse/JMV-3570
Agregar la key `hideEmptyColumns` que sea de tipo boolean y tenga `false` como valor por default
Se agregó la key correspondiente en el archivo _lib/schemas/monitor/schema.js_
Ingresar a la branch, correr los tests:
`yml: node index.js validate -i tests/mocks/schemas/monitor.yml`
`json: node index.js validate -i tests/mocks/schemas/expected/monitor.json`
```
- hideEmptyColumns key in monitor schema
```

JMV-3573-ocultar-columnas-vacias-en-monitor

---

lib/schemas/common/actions/action.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

https://janiscommerce.atlassian.net/browse/JMV-3542
Agregar la key `modalTitle` al schema del action sólo cuando el callback es `openModal`
- Se agregó la nueva key al schema correspondiente
Ingresar a la branch, correr los tests, ejemplo:
yml: `node index.js validate -i tests/mocks/schemas/edit.yml`
json: `node index.js validate -i tests/mocks/schemas/expected/edit.json`
```
- modalTitle key in action schema
```

JMV-3557-implementacion-componente-para-resetear-contraseña

---

lib/schemas/browse/modules/field-appearance.js
lib/schemas/common/width.js
lib/schemas/definitions/index.js
lib/schemas/edit-new/modules/field.js
tests/mocks/schemas/edit.yml
tests/mocks/schemas/expected/edit.json

- No hay, se generó a traves de [una consulta del canal de slack](https://janiscommerce.slack.com/archives/CASE3VALU/p1728471146811969)
- Se necesita que el `field` utilizado en las secciones de los `edit/new`, permitan utilizar la prop `width` que ya tienen pero aceptando ademas de numero un `string`
Esto por lo visto ya está utilizándose y de hecho encontré el caso del `field-appearance`, que ya tiene armado el `oneOf` que necesitamos
**El funcionamiento del width debe ser**
- Debe poder recibir un número. Si lo recibe, del lado de `Views` aplicamos ese numero como porcentaje (**50**)
-  Debe poder recibir un `string` pero ese `string` debe ser `auto`, o un número que termine con **px** o **%**, ya que si el valor que llegue es texto, se utiliza desde `Views` directamente como el …

add width definition

---

lib/schemas/browse/modules/filters/components/select.js
lib/schemas/edit-new/modules/components/selectMultilevel.js
lib/schemas/edit-new/modules/components/selects.js
tests/mocks/schemas/browse.json
tests/mocks/schemas/edit-with-actions-source.yml
tests/mocks/schemas/edit-with-sources.yml
tests/mocks/schemas/expected/browse.json
tests/mocks/schemas/expected/edit-with-actions-source.json
tests/mocks/schemas/expected/edit-with-sources.json

https://janiscommerce.atlassian.net/browse/JMV-3633
Se requiere agregar la key imageField para poder agregar imagenes a Select y Multiselect 
- Se agrego la key imageField al schema de Select y Multiselect
- Se agregaron casos de prueba para browse 
- Entrar a la rama 
- Correr el comando npm run test
- Deben pasar los test con la key
- Quitar imageField de los test browse.json y de expected/browse.json 
- Volver a correr el comando npm run test
- Deben pasar los test sin la key
- Quitar imageField de los test edit-with-source.yml y de expected/edit-with-source.json
- Volver a correr el comando npm run test
- Deben pasar los test sin la key
- Quitar imageField de los test de edit-with-actions-source.yml y de expected/edit-with-actions-source.json
- Volver a correr el comando npm run test …

Added key imageFieldName to Select and Multiselect components

---

lib/schemas/settings/modules/sectionNames.js

- https://janiscommerce.atlassian.net/browse/JMV-3657
- Permitir que a las secciones de la vista Settings, se le pueda pasar un BrowseSection
- Se agregó la key en las permitidas
- Ingresando a la rama y corriendo el comando npm run test
- Agregando un browse section en el mock de settings tanto en json como en yml
```
BrowseSection at settings
- 
- 
- 
- 
- 
```

add browseSection to setting posibilities at sections

---

lib/schemas/common/graphs.js
tests/mocks/schemas/dashboard-with-links.yml
tests/mocks/schemas/expected/dashboard-with-links.json
tests/validator-test.js

https://janiscommerce.atlassian.net/browse/JMV-3718
Se requiere agregar la key link de tipo string a los Chart (graph) de dashboard
- Se agrego la key link de tipo string a graphs de dashboard y se agregaron los test necesarios para probarlo
- Verificar los test nuevos y ver que todos los tipos de graph tienen link y un TextCardKpi repetido no lo tiene para validar que funcione sin link
- Correr npm run test 
- Luego ir jugando con la key link probando otros tipos y quitandolo de los distintos graphs y ver que todo funcione bien corriendo npm run test las veces necesarias
-
-
```
- Link key to dashboard graphs
- 
- 
- 
- 
```

Added link to dashboard graphs

---

lib/schemas/browse/modules/components/chips.js
lib/schemas/edit-new/modules/componentNames.js
lib/schemas/edit-new/modules/components/chips.js

- [JMV-3898](https://janiscommerce.atlassian.net/browse/JMV-3898)
- Agregar soporte para `themeConditionals` en el componente `smallChip` para permitir la aplicación condicional de temas basados en diferentes condiciones
- Incluir `smallChip` como componente válido en los esquemas de validación para las vistas de edit y new
- Extender la funcionalidad de chips para soportar configuraciones de tema condicionales
- El componente `smallChip` debe soportar la propiedad `themeConditionals`
- Los esquemas de validación deben incluir `smallChip` como componente válido
- La funcionalidad debe mantener compatibilidad con componentes existentes
- Los tests deben pasar correctamente
- Se agregó la propiedad `themeConditionals` al componente `smallChip` en los esquemas de browse y edit-new
- Se …

Jmv 3898 add theme conditionals at validator
